;;; bw-large-c
;;;
;;; Initial:  C/B/A/L/M/   K/J/E/D/AD/AE/   I/H/G/F
;;; Goal:     AD/A/E/J/   AE/M/H/I/D/   L/B/C/K/G/F/
;;; Length:   BH

(define (problem bw-large-c)
  (:domain prodigy-bw)
  (:objects A B C D E F G H I J K L M N O)
  (:init (arm-empty)
	 (on C B)
	 (on B A)
	 (on A L)
	 (on L M)
	 (on-table M)
	 (on K J)
	 (on J E)
	 (on E D)
	 (on D N)
	 (on N O)
	 (on-table O)
	 (on I H)
	 (on H G)
	 (on G F)
	 (on-table F)
	 (clear C)
	 (clear K)
	 (clear I))
  (:goal (and
	  (on N A)
	  (on A E)
	  (on E J)
	  (on-table J)
	  (on O M)
	  (on M H)
	  (on H I)
	  (on I D)
	  (on-table D)
	  (on L B)
	  (on B C)
	  (on C K)
	  (on K G)
	  (on G F)
	  (on-table F)
	  (clear N)
	  (clear O)
	  (clear L)
	  )))
