(define (problem ra) 
   (:domain rockets)
   (:objects mxf avrim alex jason pencil paper michelle april betty lisa
             r1 r2
             London JFK Boston Paris)
             
   (:init (object mxf)
	  (object avrim)
	  (object alex)
	  (object jason)
	  (object pencil)
	  (object paper)
	  (object michelle)
	  (object april)
	  (object betty)
	  (object lisa)
	  (rocket r1)
	  (rocket r2)
	  (place London)
	  (place JFK)
	  (place Boston)
	  (place Paris)
	
          (at r1 JFK)
	  (at r2 Boston)
	  (has-fuel r1)
	  (has-fuel r2)
	  (at mxf Paris)
	  (at avrim Paris)
	  (at alex Paris)
	  (at jason JFK)
	  (at pencil London)
	  (at paper London)
	  (at michelle London)
	  (at april London)
	  (at betty London)
	  (at lisa London))
   (:goal (AND  (at mxf Boston)  
		(at avrim JFK)
		(at pencil Boston)
		(at alex JFK)
		(at april Boston)
		(at lisa Paris)
		(at michelle JFK)
		(at jason Boston)
		(at paper Paris)
		(at betty JFK))))
