
#line 3 "lex.dis_fct_pddl.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer dis_fct_pddl_create_buffer
#define yy_delete_buffer dis_fct_pddl_delete_buffer
#define yy_flex_debug dis_fct_pddl_flex_debug
#define yy_init_buffer dis_fct_pddl_init_buffer
#define yy_flush_buffer dis_fct_pddl_flush_buffer
#define yy_load_buffer_state dis_fct_pddl_load_buffer_state
#define yy_switch_to_buffer dis_fct_pddl_switch_to_buffer
#define yyin dis_fct_pddlin
#define yyleng dis_fct_pddlleng
#define yylex dis_fct_pddllex
#define yylineno dis_fct_pddllineno
#define yyout dis_fct_pddlout
#define yyrestart dis_fct_pddlrestart
#define yytext dis_fct_pddltext
#define yywrap dis_fct_pddlwrap
#define yyalloc dis_fct_pddlalloc
#define yyrealloc dis_fct_pddlrealloc
#define yyfree dis_fct_pddlfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE dis_fct_pddlrestart(dis_fct_pddlin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t dis_fct_pddlleng;

extern FILE *dis_fct_pddlin, *dis_fct_pddlout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up dis_fct_pddltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up dis_fct_pddltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via dis_fct_pddlrestart()), so that the user can continue scanning by
	 * just pointing dis_fct_pddlin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when dis_fct_pddltext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t dis_fct_pddlleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow dis_fct_pddlwrap()'s to do buffer switches
 * instead of setting up a fresh dis_fct_pddlin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void dis_fct_pddlrestart (FILE *input_file  );
void dis_fct_pddl_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE dis_fct_pddl_create_buffer (FILE *file,int size  );
void dis_fct_pddl_delete_buffer (YY_BUFFER_STATE b  );
void dis_fct_pddl_flush_buffer (YY_BUFFER_STATE b  );
void dis_fct_pddlpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void dis_fct_pddlpop_buffer_state (void );

static void dis_fct_pddlensure_buffer_stack (void );
static void dis_fct_pddl_load_buffer_state (void );
static void dis_fct_pddl_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER dis_fct_pddl_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE dis_fct_pddl_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE dis_fct_pddl_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE dis_fct_pddl_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *dis_fct_pddlalloc (yy_size_t  );
void *dis_fct_pddlrealloc (void *,yy_size_t  );
void dis_fct_pddlfree (void *  );

#define yy_new_buffer dis_fct_pddl_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        dis_fct_pddlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            dis_fct_pddl_create_buffer(dis_fct_pddlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        dis_fct_pddlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            dis_fct_pddl_create_buffer(dis_fct_pddlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *dis_fct_pddlin = (FILE *) 0, *dis_fct_pddlout = (FILE *) 0;

typedef int yy_state_type;

extern int dis_fct_pddllineno;

int dis_fct_pddllineno = 1;

extern char *dis_fct_pddltext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr dis_fct_pddltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up dis_fct_pddltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	dis_fct_pddlleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 49
#define YY_END_OF_BUFFER 50
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[208] =
    {   0,
       36,   36,    0,    0,    0,    0,   50,   48,   43,   41,
        1,    2,   32,   31,   30,   36,   33,   36,   48,   39,
       25,   27,   29,   48,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   49,   40,   42,   45,   44,   46,
       47,    0,    0,    0,    0,    0,   36,   36,   36,   34,
       34,   34,   34,   34,   34,   34,   39,   38,   26,   28,
       35,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       21,   34,   34,    0,    0,    0,    0,    0,    0,    0,
        0,   34,   34,   34,   34,   34,   34,   35,   19,    0,
       34,   34,   34,   34,   34,   24,   34,   34,   34,    0,

        0,    0,    0,    0,    0,    0,   34,   34,   34,   34,
       34,   34,    0,   18,   34,   34,   34,   34,   34,   34,
       34,   34,    0,   40,    0,    0,    0,    0,    0,    0,
       34,   11,   13,   34,   34,   34,   18,   18,   34,   34,
       34,   20,   34,   34,   34,   34,    0,   44,    0,    0,
        0,    0,    0,   34,   34,   34,   34,   18,    6,   23,
       22,   34,   34,   34,   34,    0,    0,    0,    0,    0,
       14,   12,   34,   34,   34,   34,    7,   34,    0,    4,
        0,    0,   37,   10,   34,   34,   34,   34,   17,    0,
        0,   34,   34,   34,    8,    0,    0,    9,   34,   15,

        0,    3,   16,    0,    0,    5,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    5,
        6,    7,    8,    1,    9,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,   15,
       16,   17,   18,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   41,
       44,    1,   44,   45,   46,    1,   19,   20,   21,   22,

       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   41,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[47] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    1,    2
    } ;

static yyconst flex_uint16_t yy_base[217] =
    {   0,
        0,    0,   44,   46,   48,   52,  266,  267,  267,  267,
       50,  267,  267,  267,   54,  253,  267,   50,   43,  261,
      247,  267,  246,    0,   29,    0,  238,  218,  226,   38,
      225,  221,  220,  228,  209,  267,  208,  207,  267,  206,
      205,   69,   49,  217,   76,   71,  236,   74,  235,    0,
      213,  212,  212,  220,  222,  214,  237,  267,  267,  267,
        0,    0,  217,  236,  213,  209,  199,  200,  224,  194,
        0,   60,  193,  226,  224,  186,  204,  203,  216,   85,
      197,  192,  203,  194,  182,  191,  180,    0,    0,   86,
      190,  179,  196,  184,  173,    0,  188,  191,  171,  206,

      202,  169,  174,  170,  170,  165,  183,  171,  162,  163,
      175,  158,   87,   80,  164,  157,  164,  150,  165,  168,
      160,  170,  143,  267,  184,  163,  160,  145,  164,  156,
      154,    0,    0,  153,  158,  159,  165,   85,  153,  138,
      144,    0,  140,  136,  148,  132,  124,  267,  136,  129,
      139,  144,  141,  131,  141,  123,  122,  147,    0,    0,
        0,  128,  134,  125,  128,  132,  127,  116,  122,  114,
        0,    0,  112,  121,  128,  114,    0,  112,  107,  267,
      120,  123,  267,    0,  108,  102,  118,  106,  267,  106,
      111,  103,  111,   84,    0,   83,   82,    0,   82,    0,

       71,  267,    0,   64,   64,  267,  267,  108,  112,   97,
      116,   88,  119,  121,  125,  129
    } ;

static yyconst flex_int16_t yy_def[217] =
    {   0,
      207,    1,  208,  208,  209,  209,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  210,  211,
      207,  207,  207,  212,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  213,
      213,  213,  213,  213,  213,  213,  211,  207,  207,  207,
      214,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  207,  207,  207,  207,  207,  207,  207,
      207,  213,  213,  213,  213,  213,  213,  214,  213,  207,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  215,

      207,  207,  207,  207,  207,  207,  213,  213,  213,  213,
      213,  213,  207,  207,  213,  213,  213,  213,  213,  213,
      213,  213,  207,  207,  216,  207,  207,  207,  207,  207,
      213,  213,  213,  213,  213,  213,  207,  207,  213,  213,
      213,  213,  213,  213,  213,  213,  207,  207,  207,  207,
      207,  207,  207,  213,  213,  213,  213,  207,  213,  213,
      213,  213,  213,  213,  213,  207,  207,  207,  207,  207,
      213,  213,  213,  213,  213,  213,  213,  213,  207,  207,
      207,  207,  207,  213,  213,  213,  213,  213,  207,  207,
      207,  213,  213,  213,  213,  207,  207,  213,  213,  213,

      207,  207,  213,  207,  207,  207,    0,  207,  207,  207,
      207,  207,  207,  207,  207,  207
    } ;

static yyconst flex_uint16_t yy_nxt[314] =
    {   0,
        8,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       26,   27,   28,   29,   26,   26,   30,   26,   26,   26,
       26,   31,   32,   33,   26,   26,   34,   26,   26,   26,
       26,   26,   26,    8,    8,    8,   36,   37,   36,   37,
       39,   42,   40,   41,   39,   45,   40,   41,   46,   47,
       63,   48,   43,   47,   51,   48,   64,   52,   68,   53,
       42,   76,   80,   54,   69,   55,   44,   45,   77,   56,
       46,   43,   97,   47,   78,   48,   80,  113,  113,  137,
       61,  138,   98,   81,  137,   44,  138,  114,  114,   50,

      206,  205,  204,  203,  202,  201,  200,   81,   35,   35,
       35,   35,   38,   38,   38,   38,   57,   57,   57,   57,
       62,   62,   88,   88,   88,  123,  123,  123,  123,  147,
      147,  147,  147,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  158,  174,
      173,  172,  171,  170,  169,  168,  167,  166,   75,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,   74,  146,  145,
      144,  143,  142,  141,  140,  139,  136,  135,  134,  133,

      132,  131,  130,  129,  128,  127,  126,  125,  124,  122,
      121,  120,  119,  118,  117,  116,  115,  112,  111,  110,
      109,  108,  107,  106,  105,  104,  103,  102,  101,  100,
       99,   96,   95,   94,   93,   92,   91,   90,   89,   58,
       87,   86,   85,   84,   83,   82,   49,   49,   79,   75,
       75,   75,   74,   74,   73,   72,   71,   70,   67,   66,
       65,   60,   59,   58,   49,  207,    7,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,

      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207
    } ;

static yyconst flex_int16_t yy_chk[314] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    4,    4,
        5,   11,    5,    5,    6,   15,    6,    6,   15,   18,
       25,   18,   11,   15,   19,   15,   25,   19,   30,   19,
       42,   43,   46,   19,   30,   19,   11,   45,   43,   19,
       45,   42,   72,   48,   43,   48,   80,   90,  113,  114,
      212,  114,   72,   46,  138,   42,  138,   90,  113,  210,

      205,  204,  201,  199,  197,  196,  194,   80,  208,  208,
      208,  208,  209,  209,  209,  209,  211,  211,  211,  211,
      213,  213,  214,  214,  214,  215,  215,  215,  215,  216,
      216,  216,  216,  193,  192,  191,  190,  188,  187,  186,
      185,  182,  181,  179,  178,  176,  175,  174,  173,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  158,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  147,  146,
      145,  144,  143,  141,  140,  139,  137,  136,  135,  134,
      131,  130,  129,  128,  127,  126,  125,  123,  122,  121,
      120,  119,  118,  117,  116,  115,  112,  111,  110,  109,

      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       98,   97,   95,   94,   93,   92,   91,   87,   86,   85,
       84,   83,   82,   81,   79,   78,   77,   76,   75,   74,
       73,   70,   69,   68,   67,   66,   65,   64,   63,   57,
       56,   55,   54,   53,   52,   51,   49,   47,   44,   41,
       40,   38,   37,   35,   34,   33,   32,   31,   29,   28,
       27,   23,   21,   20,   16,    7,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,

      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int dis_fct_pddl_flex_debug;
int dis_fct_pddl_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *dis_fct_pddltext;
#line 1 "lex-fct_pddl.l"
/*********************************************************************

 * (C) Copyright 2008, University of Illinois, Urbana-Champaign

 *

 * All rights reserved. Use of this software is permitted ONLY for

 * non-commercial research purposes, and it may be copied only

 * for that use only. All copies must include this copyright message.

 * This software is made available AS IS, and neither the authors

 * nor the University of Illinois, make any warranty about the

 * software or its performance.

 *

 *********************************************************************/
/********************************************************************

 * File: lex-fct_pddl.l

 * Description: modified from lex-fct_pddl.l in Metric-FF

 *

 * Authors:  Chih-wei Hsu and Benjamin W. Wah

 *

 *********************************************************************/
#line 36 "lex-fct_pddl.l"
#include "dis_ff.h"
#include "dis_parse.h"
  
  /* default dis_fct_pddlwrap function - always treat EOF as an EOF  */
int dis_fct_pddlwrap() {return 1;}

int dis_gbracket_count = 0;


#line 668 "lex.dis_fct_pddl.c"

#define INITIAL 0
#define COMMENT 1
#define OVERREAD 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int dis_fct_pddllex_destroy (void );

int dis_fct_pddlget_debug (void );

void dis_fct_pddlset_debug (int debug_flag  );

YY_EXTRA_TYPE dis_fct_pddlget_extra (void );

void dis_fct_pddlset_extra (YY_EXTRA_TYPE user_defined  );

FILE *dis_fct_pddlget_in (void );

void dis_fct_pddlset_in  (FILE * _in_str  );

FILE *dis_fct_pddlget_out (void );

void dis_fct_pddlset_out  (FILE * _out_str  );

yy_size_t dis_fct_pddlget_leng (void );

char *dis_fct_pddlget_text (void );

int dis_fct_pddlget_lineno (void );

void dis_fct_pddlset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int dis_fct_pddlwrap (void );
#else
extern int dis_fct_pddlwrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( dis_fct_pddltext, dis_fct_pddlleng, 1, dis_fct_pddlout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( dis_fct_pddlin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( dis_fct_pddlin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, dis_fct_pddlin))==0 && ferror(dis_fct_pddlin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(dis_fct_pddlin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int dis_fct_pddllex (void);

#define YY_DECL int dis_fct_pddllex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after dis_fct_pddltext and dis_fct_pddlleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! dis_fct_pddlin )
			dis_fct_pddlin = stdin;

		if ( ! dis_fct_pddlout )
			dis_fct_pddlout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			dis_fct_pddlensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				dis_fct_pddl_create_buffer(dis_fct_pddlin,YY_BUF_SIZE );
		}

		dis_fct_pddl_load_buffer_state( );
		}

	{
#line 75 "lex-fct_pddl.l"


#line 891 "lex.dis_fct_pddl.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of dis_fct_pddltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 208 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 267 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 77 "lex-fct_pddl.l"
{ return(OPEN_PAREN); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 79 "lex-fct_pddl.l"
{  return(CLOSE_PAREN); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 81 "lex-fct_pddl.l"
{  dis_gbracket_count = 1;
 BEGIN OVERREAD; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 84 "lex-fct_pddl.l"
{  dis_gbracket_count = 1;
 BEGIN OVERREAD; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 87 "lex-fct_pddl.l"
{  dis_gbracket_count = 1;
 BEGIN OVERREAD; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 90 "lex-fct_pddl.l"
{  return(DEFINE_TOK); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 92 "lex-fct_pddl.l"
{  return(PROBLEM_TOK); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 94 "lex-fct_pddl.l"
{  return(SITUATION_TOK); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 96 "lex-fct_pddl.l"
{  return(BSITUATION_TOK); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 98 "lex-fct_pddl.l"
{  return(OBJECTS_TOK); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "lex-fct_pddl.l"
{  return(GOAL_TOK); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 102 "lex-fct_pddl.l"
{  return(METRIC_TOK); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 104 "lex-fct_pddl.l"
{  return(INIT_TOK); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 106 "lex-fct_pddl.l"
{  return(BDOMAIN_TOK); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 108 "lex-fct_pddl.l"
{ return(PREFERENCE_TOK); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 109 "lex-fct_pddl.l"
{ return IS_VIOLATED_TOK; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 111 "lex-fct_pddl.l"
{  dis_gbracket_count = 1;
 BEGIN OVERREAD; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 114 "lex-fct_pddl.l"
{ strcpy(yylval.string, dis_fct_pddltext );return (AT_TOK); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 116 "lex-fct_pddl.l"
{  return(dis_AND_TOK); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 118 "lex-fct_pddl.l"
{  return(IMPLY_TOK); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 120 "lex-fct_pddl.l"
{  return(dis_OR_TOK); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 122 "lex-fct_pddl.l"
{  return(Fdis_ORdis_ALL_TOK); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 124 "lex-fct_pddl.l"
{  return(dis_EXISTS_TOK); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 126 "lex-fct_pddl.l"
{  return(dis_NOT_TOK); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 128 "lex-fct_pddl.l"
{  return(LE_TOK); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 130 "lex-fct_pddl.l"
{  return(LEQ_TOK); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 132 "lex-fct_pddl.l"
{  return(EQ_TOK); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 134 "lex-fct_pddl.l"
{  return(GEQ_TOK); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 136 "lex-fct_pddl.l"
{  return(GE_TOK); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 138 "lex-fct_pddl.l"
{  return(MINUS_TOK); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 140 "lex-fct_pddl.l"
{  return(AD_TOK); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 142 "lex-fct_pddl.l"
{  return(MU_TOK); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 144 "lex-fct_pddl.l"
{  return(DI_TOK); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 146 "lex-fct_pddl.l"
{ dis_strupcase( dis_fct_pddltext );  
  strcpy(yylval.string, dis_fct_pddltext ); return(NAME); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 149 "lex-fct_pddl.l"
{dis_strupcase( dis_fct_pddltext );
 strcpy(yylval.string, dis_fct_pddltext); return(VARIABLE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 152 "lex-fct_pddl.l"
{ strcpy(yylval.string, dis_fct_pddltext); return(NUM);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 154 "lex-fct_pddl.l"
{ return(EITHER_TOK); }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 156 "lex-fct_pddl.l"
{  dis_lineno++; } 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 157 "lex-fct_pddl.l"
{  /* this will hold only in files that end with
		   a comment but no linefeed */ } 
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 160 "lex-fct_pddl.l"
{  dis_lineno++; }  ;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 162 "lex-fct_pddl.l"
{ BEGIN COMMENT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 164 "lex-fct_pddl.l"
{ BEGIN INITIAL;}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 166 "lex-fct_pddl.l"
{  dis_lineno++; } 
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 168 "lex-fct_pddl.l"
{  dis_lineno++; }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 170 "lex-fct_pddl.l"
{  }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 172 "lex-fct_pddl.l"
{  dis_gbracket_count++; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 174 "lex-fct_pddl.l"
{  dis_gbracket_count--; 
  if (!dis_gbracket_count) BEGIN INITIAL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 177 "lex-fct_pddl.l"
{}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 178 "lex-fct_pddl.l"
ECHO;
	YY_BREAK
#line 1206 "lex.dis_fct_pddl.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(OVERREAD):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed dis_fct_pddlin at a new source and called
			 * dis_fct_pddllex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = dis_fct_pddlin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( dis_fct_pddlwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * dis_fct_pddltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of dis_fct_pddllex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					dis_fct_pddlrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			dis_fct_pddlrestart(dis_fct_pddlin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) dis_fct_pddlrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 208 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 208 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 207);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up dis_fct_pddltext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					dis_fct_pddlrestart(dis_fct_pddlin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( dis_fct_pddlwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve dis_fct_pddltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void dis_fct_pddlrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        dis_fct_pddlensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            dis_fct_pddl_create_buffer(dis_fct_pddlin,YY_BUF_SIZE );
	}

	dis_fct_pddl_init_buffer(YY_CURRENT_BUFFER,input_file );
	dis_fct_pddl_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void dis_fct_pddl_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		dis_fct_pddlpop_buffer_state();
	 *		dis_fct_pddlpush_buffer_state(new_buffer);
     */
	dis_fct_pddlensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	dis_fct_pddl_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (dis_fct_pddlwrap()) processing, but the only time this flag
	 * is looked at is after dis_fct_pddlwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void dis_fct_pddl_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	dis_fct_pddlin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE dis_fct_pddl_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) dis_fct_pddlalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in dis_fct_pddl_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) dis_fct_pddlalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in dis_fct_pddl_create_buffer()" );

	b->yy_is_our_buffer = 1;

	dis_fct_pddl_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with dis_fct_pddl_create_buffer()
 * 
 */
    void dis_fct_pddl_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		dis_fct_pddlfree((void *) b->yy_ch_buf  );

	dis_fct_pddlfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a dis_fct_pddlrestart() or at EOF.
 */
    static void dis_fct_pddl_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	dis_fct_pddl_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then dis_fct_pddl_init_buffer was _probably_
     * called from dis_fct_pddlrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void dis_fct_pddl_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		dis_fct_pddl_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void dis_fct_pddlpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	dis_fct_pddlensure_buffer_stack();

	/* This block is copied from dis_fct_pddl_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from dis_fct_pddl_switch_to_buffer. */
	dis_fct_pddl_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void dis_fct_pddlpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	dis_fct_pddl_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		dis_fct_pddl_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void dis_fct_pddlensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)dis_fct_pddlalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in dis_fct_pddlensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)dis_fct_pddlrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in dis_fct_pddlensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE dis_fct_pddl_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) dis_fct_pddlalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in dis_fct_pddl_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	dis_fct_pddl_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to dis_fct_pddllex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       dis_fct_pddl_scan_bytes() instead.
 */
YY_BUFFER_STATE dis_fct_pddl_scan_string (yyconst char * yystr )
{
    
	return dis_fct_pddl_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to dis_fct_pddllex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE dis_fct_pddl_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) dis_fct_pddlalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in dis_fct_pddl_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = dis_fct_pddl_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in dis_fct_pddl_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up dis_fct_pddltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		dis_fct_pddltext[dis_fct_pddlleng] = (yy_hold_char); \
		(yy_c_buf_p) = dis_fct_pddltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		dis_fct_pddlleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int dis_fct_pddlget_lineno  (void)
{
        
    return dis_fct_pddllineno;
}

/** Get the input stream.
 * 
 */
FILE *dis_fct_pddlget_in  (void)
{
        return dis_fct_pddlin;
}

/** Get the output stream.
 * 
 */
FILE *dis_fct_pddlget_out  (void)
{
        return dis_fct_pddlout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t dis_fct_pddlget_leng  (void)
{
        return dis_fct_pddlleng;
}

/** Get the current token.
 * 
 */

char *dis_fct_pddlget_text  (void)
{
        return dis_fct_pddltext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void dis_fct_pddlset_lineno (int  _line_number )
{
    
    dis_fct_pddllineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see dis_fct_pddl_switch_to_buffer
 */
void dis_fct_pddlset_in (FILE *  _in_str )
{
        dis_fct_pddlin = _in_str ;
}

void dis_fct_pddlset_out (FILE *  _out_str )
{
        dis_fct_pddlout = _out_str ;
}

int dis_fct_pddlget_debug  (void)
{
        return dis_fct_pddl_flex_debug;
}

void dis_fct_pddlset_debug (int  _bdebug )
{
        dis_fct_pddl_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from dis_fct_pddllex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    dis_fct_pddlin = stdin;
    dis_fct_pddlout = stdout;
#else
    dis_fct_pddlin = (FILE *) 0;
    dis_fct_pddlout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * dis_fct_pddllex_init()
     */
    return 0;
}

/* dis_fct_pddllex_destroy is for both reentrant and non-reentrant scanners. */
int dis_fct_pddllex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		dis_fct_pddl_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		dis_fct_pddlpop_buffer_state();
	}

	/* Destroy the stack itself. */
	dis_fct_pddlfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * dis_fct_pddllex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *dis_fct_pddlalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *dis_fct_pddlrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void dis_fct_pddlfree (void * ptr )
{
			free( (char *) ptr );	/* see dis_fct_pddlrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 178 "lex-fct_pddl.l"



