
#line 3 "lex.dis_ops_pddl.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer dis_ops_pddl_create_buffer
#define yy_delete_buffer dis_ops_pddl_delete_buffer
#define yy_flex_debug dis_ops_pddl_flex_debug
#define yy_init_buffer dis_ops_pddl_init_buffer
#define yy_flush_buffer dis_ops_pddl_flush_buffer
#define yy_load_buffer_state dis_ops_pddl_load_buffer_state
#define yy_switch_to_buffer dis_ops_pddl_switch_to_buffer
#define yyin dis_ops_pddlin
#define yyleng dis_ops_pddlleng
#define yylex dis_ops_pddllex
#define yylineno dis_ops_pddllineno
#define yyout dis_ops_pddlout
#define yyrestart dis_ops_pddlrestart
#define yytext dis_ops_pddltext
#define yywrap dis_ops_pddlwrap
#define yyalloc dis_ops_pddlalloc
#define yyrealloc dis_ops_pddlrealloc
#define yyfree dis_ops_pddlfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE dis_ops_pddlrestart(dis_ops_pddlin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t dis_ops_pddlleng;

extern FILE *dis_ops_pddlin, *dis_ops_pddlout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up dis_ops_pddltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up dis_ops_pddltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via dis_ops_pddlrestart()), so that the user can continue scanning by
	 * just pointing dis_ops_pddlin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when dis_ops_pddltext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t dis_ops_pddlleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow dis_ops_pddlwrap()'s to do buffer switches
 * instead of setting up a fresh dis_ops_pddlin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void dis_ops_pddlrestart (FILE *input_file  );
void dis_ops_pddl_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE dis_ops_pddl_create_buffer (FILE *file,int size  );
void dis_ops_pddl_delete_buffer (YY_BUFFER_STATE b  );
void dis_ops_pddl_flush_buffer (YY_BUFFER_STATE b  );
void dis_ops_pddlpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void dis_ops_pddlpop_buffer_state (void );

static void dis_ops_pddlensure_buffer_stack (void );
static void dis_ops_pddl_load_buffer_state (void );
static void dis_ops_pddl_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER dis_ops_pddl_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE dis_ops_pddl_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE dis_ops_pddl_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE dis_ops_pddl_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *dis_ops_pddlalloc (yy_size_t  );
void *dis_ops_pddlrealloc (void *,yy_size_t  );
void dis_ops_pddlfree (void *  );

#define yy_new_buffer dis_ops_pddl_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        dis_ops_pddlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            dis_ops_pddl_create_buffer(dis_ops_pddlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        dis_ops_pddlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            dis_ops_pddl_create_buffer(dis_ops_pddlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *dis_ops_pddlin = (FILE *) 0, *dis_ops_pddlout = (FILE *) 0;

typedef int yy_state_type;

extern int dis_ops_pddllineno;

int dis_ops_pddllineno = 1;

extern char *dis_ops_pddltext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr dis_ops_pddltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up dis_ops_pddltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	dis_ops_pddlleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[275] =
    {   0,
       48,   48,    0,    0,    0,    0,   62,   60,   55,   53,
       60,    1,    2,   32,   31,   30,   48,   33,   48,   60,
       51,   25,   27,   29,   60,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   61,   52,   54,   57,   56,
       58,   59,   34,    0,    0,   48,   48,   48,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   51,
       50,   26,   28,   47,   47,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   22,   46,   46,   46,
        0,    0,    0,    0,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   47,   47,   18,   46,

        0,   46,   46,   46,   46,   46,   46,   46,   19,   46,
       46,   46,    0,    0,    0,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   47,   46,    0,
        0,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       20,    0,   52,    0,    0,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   12,   47,
       46,    0,    0,   46,   46,   46,   46,   46,   21,   46,
        0,   46,    0,   56,    0,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,    6,   47,   35,
       44,    0,   46,    3,    4,   24,   23,   46,    0,   46,

        0,   10,   46,   46,   46,   46,   15,   46,   46,   46,
       46,   46,   46,   47,    0,   46,   46,    0,   46,   46,
       49,   46,   46,   17,   46,   46,   46,   16,   46,   46,
       46,   46,   47,   43,   39,   38,   45,   46,   36,   46,
       46,   40,   46,   46,   46,   46,   46,   46,   41,   46,
       14,    7,   46,    9,   46,   46,   46,   46,   37,   46,
       11,   46,    8,   46,   46,   46,   46,   46,   13,    5,
       46,   46,   42,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    1,    7,
        8,    9,   10,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,   20,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   22,   22,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   22,
       44,    1,   44,   45,   46,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   22,   22,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   22,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[47] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    1,    2
    } ;

static yyconst flex_uint16_t yy_base[283] =
    {   0,
        0,    0,   44,   45,   48,   50,  340,  341,  341,  341,
      301,  341,  341,  341,  341,   57,  324,  341,   40,   51,
      334,  318,  341,  317,  310,   28,    0,   37,  291,  299,
       36,  298,   59,  307,  301,  283,  341,  282,  281,  341,
      280,  279,  341,   94,   98,  309,   91,  308,  298,    0,
      287,   72,  293,  279,  286,   83,  291,  272,  293,  310,
      341,  341,  341,    0,  273,    0,  287,  273,  305,   83,
      277,  278,  270,  271,  281,  265,    0,  277,  280,  275,
      294,  291,  106,  268,  258,  263,  258,  257,  266,  259,
      256,  253,  263,  252,  252,  249,    0,  248,    0,  254,

       87,  246,  252,  259,  242,  257,  247,  240,    0,  239,
      244,  241,  269,  263,  232,  240,   83,  239,  246,  241,
      242,  234,  242,   90,  223,  236,  223,  238,  231,  225,
      218,  230,  222,  224,  214,  221,  207,  224,  244,  222,
        0,  201,  341,  242,  216,  210,  213,  203,  200,  201,
      215,  199,  207,  204,  201,  204,  203,  194,    0,  192,
      197,  204,  206,  205,  200,  192,  186,  192,    0,  200,
      199,  208,  173,  341,  192,  184,  177,  193,  188,  183,
      173,  181,  184,  183,  175,  183,  169,    0,  175,    0,
      341,  167,  165,    0,    0,    0,    0,  164,  170,   91,

      163,    0,  169,  165,  172,   85,    0,  162,  157,  155,
      168,  170,  165,  156,  150,  162,  161,  155,  151,  149,
      341,  149,  143,    0,  148,  154,  146,    0,  152,  147,
      137,  143,  141,  341,    0,    0,  341,  131,    0,  139,
      133,    0,  158,  131,  131,  128,  140,  139,    0,  131,
        0,    0,  141,    0,  124,  131,  122,  126,    0,  134,
        0,   96,    0,   90,   89,   94,   85,   92,    0,    0,
       84,   84,    0,  341,  131,  135,  139,   60,  142,  144,
      148,  152
    } ;

static yyconst flex_int16_t yy_def[283] =
    {   0,
      274,    1,  275,  275,  276,  276,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      277,  274,  274,  274,  278,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  277,
      274,  274,  274,  280,  280,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      274,  274,  274,  274,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  280,  280,  279,  279,

      274,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  281,  274,  274,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  280,  279,  274,
      274,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  274,  274,  282,  274,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  280,
      279,  274,  274,  279,  279,  279,  279,  279,  279,  279,
      274,  279,  274,  274,  274,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  280,  279,
      274,  274,  279,  279,  279,  279,  279,  279,  274,  279,

      274,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  280,  274,  279,  279,  274,  279,  279,
      274,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  280,  274,  279,  279,  274,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  280,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,    0,  274,  274,  274,  274,  274,  274,
      274,  274
    } ;

static yyconst flex_uint16_t yy_nxt[388] =
    {   0,
        8,    8,    9,    8,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   27,   28,   29,   30,   27,   27,   31,   27,
       27,   32,   33,   27,   27,   27,   34,   27,   27,   27,
       35,   27,   27,    8,    8,    8,   37,   37,   38,   38,
       40,   46,   40,   47,   41,   42,   41,   42,   44,   67,
       44,   70,   64,   45,   68,   69,   74,   75,   46,   71,
       47,   49,   50,   51,   52,   53,   54,   50,   50,   55,
       50,   50,   50,   50,   56,   50,   57,   50,   58,   50,
       59,   50,   50,   50,   77,   44,   87,   44,   78,   83,

       45,   83,   46,   92,   47,  102,  147,   83,  103,   83,
       88,  130,  155,  156,  219,  273,  272,  225,   93,  148,
      271,  270,   84,  131,  226,  269,  268,  267,  266,  220,
       84,   36,   36,   36,   36,   39,   39,   39,   39,   60,
       60,   60,   60,   66,   66,   97,   97,   97,  142,  142,
      142,  142,  173,  173,  173,  173,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  224,  223,  222,  221,  218,

      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,   82,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,   81,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  154,  153,  152,  151,  150,  149,  146,  145,
      144,  143,  141,  140,  139,  138,  137,  136,  135,  134,
      133,  132,  129,  128,  127,  126,  125,  124,  123,  122,
      121,  120,  119,  118,  117,  116,  115,  114,  113,  112,

      111,  110,  109,  108,  107,  106,  105,  104,  101,  100,
       99,   98,   61,   96,   95,   94,   91,   90,   89,   86,
       85,   48,   48,   82,   82,   82,   81,   81,   80,   79,
       76,   73,   72,   65,   63,   62,   61,   48,   43,  274,
        7,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274
    } ;

static yyconst flex_int16_t yy_chk[388] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    3,    4,
        5,   19,    6,   19,    5,    5,    6,    6,   16,   26,
       16,   28,  278,   16,   26,   26,   31,   31,   16,   28,
       16,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   33,   44,   52,   44,   33,   45,

       44,   45,   47,   56,   47,   70,  117,   83,   70,   83,
       52,  101,  124,  124,  200,  272,  271,  206,   56,  117,
      268,  267,   45,  101,  206,  266,  265,  264,  262,  200,
       83,  275,  275,  275,  275,  276,  276,  276,  276,  277,
      277,  277,  277,  279,  279,  280,  280,  280,  281,  281,
      281,  281,  282,  282,  282,  282,  260,  258,  257,  256,
      255,  253,  250,  248,  247,  246,  245,  244,  243,  241,
      240,  238,  233,  232,  231,  230,  229,  227,  226,  225,
      223,  222,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  205,  204,  203,  201,  199,

      198,  193,  192,  189,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  173,  172,  171,
      170,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  145,  144,  142,  140,  139,  138,  137,
      136,  135,  134,  133,  132,  131,  130,  129,  128,  127,
      126,  125,  123,  122,  121,  120,  119,  118,  116,  115,
      114,  113,  112,  111,  110,  108,  107,  106,  105,  104,
      103,  102,  100,   98,   96,   95,   94,   93,   92,   91,
       90,   89,   88,   87,   86,   85,   84,   82,   81,   80,

       79,   78,   76,   75,   74,   73,   72,   71,   69,   68,
       67,   65,   60,   59,   58,   57,   55,   54,   53,   51,
       49,   48,   46,   42,   41,   39,   38,   36,   35,   34,
       32,   30,   29,   25,   24,   22,   21,   17,   11,    7,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int dis_ops_pddl_flex_debug;
int dis_ops_pddl_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *dis_ops_pddltext;
#line 1 "lex-ops_pddl.l"
/*********************************************************************

 * (C) Copyright 2008, University of Illinois, Urbana-Champaign

 *

 * All rights reserved. Use of this software is permitted ONLY for

 * non-commercial research purposes, and it may be copied only

 * for that use only. All copies must include this copyright message.

 * This software is made available AS IS, and neither the authors

 * nor the University of Illinois, make any warranty about the

 * software or its performance.

 *

 *********************************************************************/
/********************************************************************

 * File: lex-ops_pddl.l 

 * Description: modified from lex-ops_pddl.l in Metric-FF

 *

 * Authors:  Chih-wei Hsu and Benjamin W. Wah

 *

 *********************************************************************/
#line 36 "lex-ops_pddl.l"
#include "dis_ff.h"
#include "dis_parse.h"

/* default dis_ops_pddlwrap function - always treat EOF as an EOF  */
int dis_ops_pddlwrap() {return 1;}


#line 701 "lex.dis_ops_pddl.c"

#define INITIAL 0
#define COMMENT 1
#define OVERREAD 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int dis_ops_pddllex_destroy (void );

int dis_ops_pddlget_debug (void );

void dis_ops_pddlset_debug (int debug_flag  );

YY_EXTRA_TYPE dis_ops_pddlget_extra (void );

void dis_ops_pddlset_extra (YY_EXTRA_TYPE user_defined  );

FILE *dis_ops_pddlget_in (void );

void dis_ops_pddlset_in  (FILE * _in_str  );

FILE *dis_ops_pddlget_out (void );

void dis_ops_pddlset_out  (FILE * _out_str  );

yy_size_t dis_ops_pddlget_leng (void );

char *dis_ops_pddlget_text (void );

int dis_ops_pddlget_lineno (void );

void dis_ops_pddlset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int dis_ops_pddlwrap (void );
#else
extern int dis_ops_pddlwrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( dis_ops_pddltext, dis_ops_pddlleng, 1, dis_ops_pddlout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( dis_ops_pddlin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( dis_ops_pddlin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, dis_ops_pddlin))==0 && ferror(dis_ops_pddlin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(dis_ops_pddlin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int dis_ops_pddllex (void);

#define YY_DECL int dis_ops_pddllex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after dis_ops_pddltext and dis_ops_pddlleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! dis_ops_pddlin )
			dis_ops_pddlin = stdin;

		if ( ! dis_ops_pddlout )
			dis_ops_pddlout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			dis_ops_pddlensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				dis_ops_pddl_create_buffer(dis_ops_pddlin,YY_BUF_SIZE );
		}

		dis_ops_pddl_load_buffer_state( );
		}

	{
#line 73 "lex-ops_pddl.l"


#line 924 "lex.dis_ops_pddl.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of dis_ops_pddltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 275 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 341 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 75 "lex-ops_pddl.l"
{  return(OPEN_PAREN); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 77 "lex-ops_pddl.l"
{  return(CLOSE_PAREN); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 79 "lex-ops_pddl.l"
{  return(DEFINE_TOK); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 81 "lex-ops_pddl.l"
{  return(DOMAIN_TOK); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 83 "lex-ops_pddl.l"
{  return(REQUIREMENTS_TOK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 85 "lex-ops_pddl.l"
{  return(TYPES_TOK); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 87 "lex-ops_pddl.l"
{  return(CONSTANTS_TOK); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 89 "lex-ops_pddl.l"
{ return(PREDICATES_TOK); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 91 "lex-ops_pddl.l"
{ return(FUNCTIONS_TOK); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 93 "lex-ops_pddl.l"
{  return(ACTION_TOK); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 95 "lex-ops_pddl.l"
{  return(PARAMETERS_TOK); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "lex-ops_pddl.l"
{ return(VARS_TOK); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 99 "lex-ops_pddl.l"
{  return(PRECONDITION_TOK); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 101 "lex-ops_pddl.l"
{ return(CONDITION_TOK); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 103 "lex-ops_pddl.l"
{  return(EFFECT_TOK); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 105 "lex-ops_pddl.l"
{  return(IMPLIES_TOK); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 107 "lex-ops_pddl.l"
{ return(DERIVED_TOK); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 109 "lex-ops_pddl.l"
{  return(dis_AND_TOK); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 111 "lex-ops_pddl.l"
{  return(dis_NOT_TOK); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 113 "lex-ops_pddl.l"
{  return(dis_WHEN_TOK); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 115 "lex-ops_pddl.l"
{  return(IMPLY_TOK); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 117 "lex-ops_pddl.l"
{  return(dis_OR_TOK); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 119 "lex-ops_pddl.l"
{  return(Fdis_ORdis_ALL_TOK); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 121 "lex-ops_pddl.l"
{  return(dis_EXISTS_TOK); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 123 "lex-ops_pddl.l"
{  return(LE_TOK); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 125 "lex-ops_pddl.l"
{  return(LEQ_TOK); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 127 "lex-ops_pddl.l"
{  return(EQ_TOK); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 129 "lex-ops_pddl.l"
{  return(GEQ_TOK); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 131 "lex-ops_pddl.l"
{  return(GE_TOK); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 133 "lex-ops_pddl.l"
{  return(MINUS_TOK); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 135 "lex-ops_pddl.l"
{  return(AD_TOK); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 137 "lex-ops_pddl.l"
{  return(MU_TOK); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 139 "lex-ops_pddl.l"
{  return(DI_TOK); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 141 "lex-ops_pddl.l"
{ return (TIME_TOK);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 143 "lex-ops_pddl.l"
{ return(ASSIGN_TOK); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 145 "lex-ops_pddl.l"
{ return(SCALE_UP_TOK); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 147 "lex-ops_pddl.l"
{ return(SCALE_DOWN_TOK); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 149 "lex-ops_pddl.l"
{ return(INCREASE_TOK); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 151 "lex-ops_pddl.l"
{ return(DECREASE_TOK); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 153 "lex-ops_pddl.l"
{ return (DURATION_TOK); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 155 "lex-ops_pddl.l"
{  return(DURATION_VAR_TOK); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 157 "lex-ops_pddl.l"
{ return (DURATIVE_ACTION_TOK); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 159 "lex-ops_pddl.l"
{return AT_START;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 161 "lex-ops_pddl.l"
{return AT_END;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 163 "lex-ops_pddl.l"
{return OVER_ALL;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 166 "lex-ops_pddl.l"
{ dis_strupcase(dis_ops_pddltext); strcpy(yylval.string, dis_ops_pddltext); 
 return(NAME); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 169 "lex-ops_pddl.l"
{ dis_strupcase(dis_ops_pddltext); strcpy(yylval.string, dis_ops_pddltext); 
 return(VARIABLE); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 172 "lex-ops_pddl.l"
{ strcpy(yylval.string, dis_ops_pddltext); return(NUM);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 175 "lex-ops_pddl.l"
{ return(EITHER_TOK); }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 177 "lex-ops_pddl.l"
{  dis_lineno++; } 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 178 "lex-ops_pddl.l"
{  /* this will hold only in files that end with
		   a comment but no linefeed */ } 
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 181 "lex-ops_pddl.l"
{  dis_lineno++; }  ;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 183 "lex-ops_pddl.l"
{ BEGIN COMMENT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 185 "lex-ops_pddl.l"
{ BEGIN INITIAL;}
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 187 "lex-ops_pddl.l"
{  dis_lineno++; } 
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 189 "lex-ops_pddl.l"
{  dis_lineno++; }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 191 "lex-ops_pddl.l"
{  }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 193 "lex-ops_pddl.l"
{  BEGIN OVERREAD; dis_gbracket_count++; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 195 "lex-ops_pddl.l"
{  BEGIN OVERREAD; dis_gbracket_count--; 
  if (!dis_gbracket_count) BEGIN INITIAL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 198 "lex-ops_pddl.l"
{}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 199 "lex-ops_pddl.l"
ECHO;
	YY_BREAK
#line 1295 "lex.dis_ops_pddl.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(OVERREAD):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed dis_ops_pddlin at a new source and called
			 * dis_ops_pddllex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = dis_ops_pddlin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( dis_ops_pddlwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * dis_ops_pddltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of dis_ops_pddllex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					dis_ops_pddlrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			dis_ops_pddlrestart(dis_ops_pddlin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) dis_ops_pddlrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 275 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 275 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 274);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up dis_ops_pddltext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					dis_ops_pddlrestart(dis_ops_pddlin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( dis_ops_pddlwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve dis_ops_pddltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void dis_ops_pddlrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        dis_ops_pddlensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            dis_ops_pddl_create_buffer(dis_ops_pddlin,YY_BUF_SIZE );
	}

	dis_ops_pddl_init_buffer(YY_CURRENT_BUFFER,input_file );
	dis_ops_pddl_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void dis_ops_pddl_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		dis_ops_pddlpop_buffer_state();
	 *		dis_ops_pddlpush_buffer_state(new_buffer);
     */
	dis_ops_pddlensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	dis_ops_pddl_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (dis_ops_pddlwrap()) processing, but the only time this flag
	 * is looked at is after dis_ops_pddlwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void dis_ops_pddl_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	dis_ops_pddlin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE dis_ops_pddl_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) dis_ops_pddlalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in dis_ops_pddl_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) dis_ops_pddlalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in dis_ops_pddl_create_buffer()" );

	b->yy_is_our_buffer = 1;

	dis_ops_pddl_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with dis_ops_pddl_create_buffer()
 * 
 */
    void dis_ops_pddl_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		dis_ops_pddlfree((void *) b->yy_ch_buf  );

	dis_ops_pddlfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a dis_ops_pddlrestart() or at EOF.
 */
    static void dis_ops_pddl_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	dis_ops_pddl_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then dis_ops_pddl_init_buffer was _probably_
     * called from dis_ops_pddlrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void dis_ops_pddl_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		dis_ops_pddl_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void dis_ops_pddlpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	dis_ops_pddlensure_buffer_stack();

	/* This block is copied from dis_ops_pddl_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from dis_ops_pddl_switch_to_buffer. */
	dis_ops_pddl_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void dis_ops_pddlpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	dis_ops_pddl_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		dis_ops_pddl_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void dis_ops_pddlensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)dis_ops_pddlalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in dis_ops_pddlensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)dis_ops_pddlrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in dis_ops_pddlensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE dis_ops_pddl_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) dis_ops_pddlalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in dis_ops_pddl_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	dis_ops_pddl_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to dis_ops_pddllex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       dis_ops_pddl_scan_bytes() instead.
 */
YY_BUFFER_STATE dis_ops_pddl_scan_string (yyconst char * yystr )
{
    
	return dis_ops_pddl_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to dis_ops_pddllex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE dis_ops_pddl_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) dis_ops_pddlalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in dis_ops_pddl_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = dis_ops_pddl_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in dis_ops_pddl_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up dis_ops_pddltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		dis_ops_pddltext[dis_ops_pddlleng] = (yy_hold_char); \
		(yy_c_buf_p) = dis_ops_pddltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		dis_ops_pddlleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int dis_ops_pddlget_lineno  (void)
{
        
    return dis_ops_pddllineno;
}

/** Get the input stream.
 * 
 */
FILE *dis_ops_pddlget_in  (void)
{
        return dis_ops_pddlin;
}

/** Get the output stream.
 * 
 */
FILE *dis_ops_pddlget_out  (void)
{
        return dis_ops_pddlout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t dis_ops_pddlget_leng  (void)
{
        return dis_ops_pddlleng;
}

/** Get the current token.
 * 
 */

char *dis_ops_pddlget_text  (void)
{
        return dis_ops_pddltext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void dis_ops_pddlset_lineno (int  _line_number )
{
    
    dis_ops_pddllineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see dis_ops_pddl_switch_to_buffer
 */
void dis_ops_pddlset_in (FILE *  _in_str )
{
        dis_ops_pddlin = _in_str ;
}

void dis_ops_pddlset_out (FILE *  _out_str )
{
        dis_ops_pddlout = _out_str ;
}

int dis_ops_pddlget_debug  (void)
{
        return dis_ops_pddl_flex_debug;
}

void dis_ops_pddlset_debug (int  _bdebug )
{
        dis_ops_pddl_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from dis_ops_pddllex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    dis_ops_pddlin = stdin;
    dis_ops_pddlout = stdout;
#else
    dis_ops_pddlin = (FILE *) 0;
    dis_ops_pddlout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * dis_ops_pddllex_init()
     */
    return 0;
}

/* dis_ops_pddllex_destroy is for both reentrant and non-reentrant scanners. */
int dis_ops_pddllex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		dis_ops_pddl_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		dis_ops_pddlpop_buffer_state();
	}

	/* Destroy the stack itself. */
	dis_ops_pddlfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * dis_ops_pddllex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *dis_ops_pddlalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *dis_ops_pddlrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void dis_ops_pddlfree (void * ptr )
{
			free( (char *) ptr );	/* see dis_ops_pddlrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 199 "lex-ops_pddl.l"



