(define (problem b3)
  (:domain blocks)
  (:objects A B C - block)
  (:init
    (and (oneof (handempty) (holding A) (holding B) (holding C))       ; (holding ?x)
         (oneof (holding A) (clear A) (on B A) (on C A))               ; (above A ?x)
         (oneof (holding A) (ontable A) (on A B) (on A C))             ; (on A ?x)
         (oneof (holding B) (clear B) (on A B) (on C B))               ; (above B ?x)
         (oneof (holding B) (ontable B) (on B A) (on B C))             ; (on B ?x)
         (oneof (holding C) (clear C) (on A C) (on B C))               ; (above C ?x)
         (oneof (holding C) (ontable C) (on C A) (on C B))             ; (on C ?x)

         (or (not (handempty)) (not (holding A)))
         (or (not (handempty)) (not (holding B)))
         (or (not (handempty)) (not (holding C)))
         (or (not (holding A)) (not (holding B)))
         (or (not (holding A)) (not (holding C)))
         (or (not (holding B)) (not (holding C)))

         (or (not (holding A)) (not (clear A)))
         (or (not (holding A)) (not (on B A)))
         (or (not (holding A)) (not (on C A)))
         (or (not (clear A)) (not (on B A)))
         (or (not (clear A)) (not (on C A)))
         (or (not (on B A)) (not (on C A)))

         (or (not (holding A)) (not (ontable A)))
         (or (not (holding A)) (not (on A B)))
         (or (not (holding A)) (not (on A C)))
         (or (not (ontable A)) (not (on A B)))
         (or (not (ontable A)) (not (on A C)))
         (or (not (on A B)) (not (on A C)))

         (or (not (holding B)) (not (clear B)))
         (or (not (holding B)) (not (on A B)))
         (or (not (holding B)) (not (on C B)))
         (or (not (clear B)) (not (on A B)))
         (or (not (clear B)) (not (on C B)))
         (or (not (on A B)) (not (on C B)))

         (or (not (holding B)) (not (ontable B)))
         (or (not (holding B)) (not (on B A)))
         (or (not (holding B)) (not (on B C)))
         (or (not (ontable B)) (not (on B A)))
         (or (not (ontable B)) (not (on B C)))
         (or (not (on B C)) (not (on B C)))

         (or (not (holding C)) (not (clear C)))
         (or (not (holding C)) (not (on A C)))
         (or (not (holding C)) (not (on B C)))
         (or (not (clear C)) (not (on A C)))
         (or (not (clear C)) (not (on B C)))
         (or (not (on A C)) (not (on B C)))

         (or (not (holding C)) (not (ontable C)))
         (or (not (holding C)) (not (on C A)))
         (or (not (holding C)) (not (on C B)))
         (or (not (ontable C)) (not (on C A)))
         (or (not (ontable C)) (not (on C B)))
         (or (not (on C A)) (not (on C B)))

         (or (not (on A B)) (not (on B A)))                            ; cycles
         (or (not (on A C)) (not (on C A)))
         (or (not (on B C)) (not (on C B)))
         (or (not (on A B)) (not (on B C)) (not (on C A)))             ; on(A,B) & on(B,C) => -on(C,A)
         (or (not (on A C)) (not (on C B)) (not (on B A)))             ; on(A,C) & on(C,B) => -on(B,A)
    )
  )
  (:goal (and (ontable A) (on B A) (on C B)))
)
