(define (domain assembly)
   (:requirements :adl)
   (:types assembly resource)   ; Individual parts are atomic assemblies
   (:predicates (available ?x - (either resource assembly))
		(complete ?a - assembly)
		(requires ?a - assembly ?r - resource)
		(committed ?r - resource ?a - assembly)
		(incorporated ?part ?whole - assembly)
		(part-of ?part ?whole - assembly)
		(to-be-removed ?part ?whole - assembly)
		(assemble-order ?part1 ?part2 ?whole - assembly)
		(transient-part ?part ?whole - assembly)
		; After ?part1 is included, ?part2 must be removed
		; for the ?whole to be complete:
		(remove-order ?part1 ?part2 ?whole - assembly))

   (:action commit
      :parameters (?res - resource ?as - assembly)
      :precondition (available ?res)
      :effect (and (not (available ?res))
		   (committed ?res ?as)))

   (:action release
      :parameters (?res - resource ?as - assembly)
      :precondition (committed ?res ?as)
      :effect (and (not (committed ?res ?as))
		   (available ?res)))
		
	   
(:action assemble1
      :parameters (?part ?whole - assembly)
      :precondition 
      (forall (?res - resource ?prev - assembly)
         (and (not (requires ?whole ?res)) 
              (part-of ?part ?whole)
              (transient-part ?part ?whole)))
      :effect (and (incorporated ?part ?whole)
		   (not (available ?part))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (transient-part ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (incorporated ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))))


(:action assemble2
      :parameters (?part ?whole - assembly)
      :precondition 
      (forall (?res - resource ?prev - assembly)
              (and (not (requires ?whole ?res)) 
                   (transient-part ?part ?whole)  
                   (available ?part) 
                   (not (assemble-order ?prev ?part ?whole))))
      :effect (and (incorporated ?part ?whole)
		   (not (available ?part))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (transient-part ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (incorporated ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))))



(:action assemble3
      :parameters (?part ?whole - assembly)
      :precondition 
      (forall (?res - resource ?prev - assembly)
              (and (not (requires ?whole ?res)) 
                   (part-of ?part ?whole)
                   (available ?part) 
                   (incorporated ?prev ?whole)))
      :effect (and (incorporated ?part ?whole)
		   (not (available ?part))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (transient-part ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (incorporated ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))))
                   


(:action assemble4
      :parameters (?part ?whole - assembly)
      :precondition 
      (forall (?res - resource ?prev - assembly)
              (and (not (requires ?whole ?res))
                   (transient-part ?part ?whole)
                   (available ?part) 
                   (incorporated ?prev ?whole)))
      :effect (and (incorporated ?part ?whole)
		   (not (available ?part))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (transient-part ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (incorporated ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))))


(:action assemble5
      :parameters (?part ?whole - assembly)
      :precondition 
      (forall (?res - resource ?prev - assembly)
              (and (committed ?res ?whole)
	           (part-of ?part ?whole)
                   (transient-part ?part ?whole)))
:effect (and (incorporated ?part ?whole)
		   (not (available ?part))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (transient-part ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (incorporated ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))))


(:action assemble6
      :parameters (?part ?whole - assembly)
      :precondition 
      (forall (?res - resource ?prev - assembly)
              (and (committed ?res ?whole)
                   (transient-part ?part ?whole)
                   (available ?part) 
                   (not (assemble-order ?prev ?part ?whole))))
      :effect (and (incorporated ?part ?whole)
		   (not (available ?part))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (transient-part ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (incorporated ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))))



(:action assemble7
      :parameters (?part ?whole - assembly)
      :precondition 
      (forall (?res - resource ?prev - assembly)
              (and (committed ?res ?whole)
                   (part-of ?part ?whole)
                   (available ?part) 
                   (incorporated ?prev ?whole)))
      :effect (and (incorporated ?part ?whole)
		   (not (available ?part))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (transient-part ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (incorporated ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))))


(:action assemble8
      :parameters (?part ?whole - assembly)
      :precondition 
      (forall (?res - resource ?prev - assembly)
              (and (committed ?res ?whole)
                   (transient-part ?part ?whole)
                   (available ?part) 
                   (incorporated ?prev ?whole)))
      :effect (and (incorporated ?part ?whole)
		   (not (available ?part))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (transient-part ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (part-of ?p ?whole))
                    (not (incorporated ?tp ?whole))))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (= ?p ?part)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (transient-part ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))
         (when (forall (?p ?tp - assembly)
               (and (not (incorporated ?tp ?whole))
                    (incorporated ?p ?whole)))
                    (and (complete ?whole)
	                 (available ?whole)))))



)




;;fuer DNF effekte:

;;A= (not (part-of ?p ?whole))
;;B= (= ?p ?part)
;;C= (incorporated ?p ?whole)
;;D= (not (transient-part ?tp ?whole))
;;E= (not (incorporated ?tp ?whole))


;;fuer DNF precond:
;;X= (not (requires ?whole ?res))
;;Y= (committed ?res ?whole)
;;A= (part-of ?part ?whole)
;;B= (transient-part ?part ?whole)
;;C= (available ?part) (not (assemble-order ?prev ?part ?whole))
;;D= (available ?part) (incorporated ?prev ?whole)
			 
				   
