#define yy_create_buffer pddl_create_buffer
#define yy_delete_buffer pddl_delete_buffer
#define yy_scan_buffer pddl_scan_buffer
#define yy_scan_string pddl_scan_string
#define yy_scan_bytes pddl_scan_bytes
#define yy_flex_debug pddl_flex_debug
#define yy_init_buffer pddl_init_buffer
#define yy_flush_buffer pddl_flush_buffer
#define yy_load_buffer_state pddl_load_buffer_state
#define yy_switch_to_buffer pddl_switch_to_buffer
#define yyin pddlin
#define yyleng pddlleng
#define yylex pddllex
#define yyout pddlout
#define yyrestart pddlrestart
#define yytext pddltext
#define yywrap pddlwrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
static yyconst short int yy_accept[538] =
    {   0,
       86,   86,   89,   88,   83,   85,   88,    1,    2,   73,
       71,   72,   74,   86,   80,   88,   77,   56,   75,   79,
       81,    3,    4,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   83,   63,   86,   87,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   84,   78,   76,   82,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   44,   81,   81,   81,
       81,   81,   87,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   82,   82,   43,   81,    0,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   48,   81,   81,
       81,   81,   81,    0,    8,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   81,    0,    0,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   49,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   55,   54,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   16,    0,    0,    0,   81,    0,    0,
       81,   81,   81,   81,   81,   81,   81,   47,   81,   81,
       81,    0,   81,   81,   81,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   28,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   20,    0,    0,   70,   36,
        0,   81,   24,   25,   81,   50,   45,   46,   81,   81,
       81,    0,   81,   81,   81,   26,    0,    0,    0,    0,
       52,    0,   38,    0,    0,    0,    0,    0,    0,    0,

        0,   57,   60,    0,    0,    0,    0,    0,    0,    0,
        0,   58,    0,    7,    9,    0,    0,   81,   81,   81,
       81,   81,    0,   51,   81,   81,   81,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   15,    0,    0,
        0,   53,    0,    0,    0,    0,   27,    0,    0,    0,
        0,   35,   67,   64,   66,   62,   61,   37,   81,   68,
       81,    0,    0,    0,    0,   42,    0,    0,    6,    0,
        0,    0,    0,    0,   59,    0,    0,    0,    0,    0,
        0,    0,   81,   81,   32,   17,    0,    0,    0,    0,
        0,    0,    0,   19,    0,   41,    0,    0,    0,    0,

        0,    0,    0,   69,   65,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   30,    0,   18,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   40,    0,   31,    0,    5,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   39,    0,    0,
        0,    0,    0,    0,    0,   29,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   21,   34,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       23,    0,    0,    0,    0,   33,    0,   14,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   22,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       12,    0,    0,   13,   10,   11,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    1,    6,
        7,    8,    9,    1,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
       17,   18,   19,    1,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       21,    1,   22,    1,   20,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   32,   20,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[48] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst short int yy_base[544] =
    {   0,
        0,    0,  781,  782,   46,  782,  739,  782,  782,  782,
      782,  766,  782,   38,   29,  775,  760,  782,  759,    0,
       51,  782,  782,   62,   63,   64,   68,   72,   70,   74,
       76,   78,   98,  103,  108,   90,  782,   85,  762,   99,
      738,   91,  102,  101,  737,  737,  744,  743,  745,   89,
      726,  740,   73,   89,  731,  762,  782,  782,  782,  116,
        0,  131,  136,  138,  146,  142,  147,  148,  153,  155,
      159,  163,  164,  169,  170,  175,  180,  182,  186,  194,
      193,  198,  751,  722,  729,  726,  720,  725,  719,  729,
      730,  713,  727,  722,  717,  709,  715,  726,  111,  713,

      706,  714,  706,  148,  721,  705,  703,  174,  707,  703,
      708,    0,  202,  208,  210,  192,  214,  216,  220,  225,
      226,  218,  227,  232,  236,  241,  242,  247,  249,  254,
      253,  258,  266,  707,  782,  243,  705,  713,  712,  707,
      723,  709,  696,  690,  706,  701,  702,  693,  684,  701,
      694,  683,  694,  697,  176,  694,  683,  675,  685,  676,
      683,  686,  234,  669,  277,  676,  669,  272,  279,  281,
      283,  290,  285,  292,  294,  300,  298,  305,  318,  310,
      306,  324,  325,  673,  677,  666,  675,  663,  673,  662,
      677,  664,  667,  658,  657,  664,  661,  654,  782,  663,

      654,  651,  660,  665,  296,  653,  657,  660,  645,  654,
      661,  642,  645,  782,  641,  645,  652,  331,  652,  654,
      332,  336,  337,  338,  343,  348,  352,  354,  358,  360,
      364,  653,  365,  366,  370,  640,  633,  650,  637,  636,
      635,  638,  627,  628,  635,  782,  638,  654,  622,  631,
      638,  629,  629,  633,  616,  623,  628,  619,  628,  612,
      620,  611,  616,  638,  607,  782,  617,  606,  374,  782,
      605,  376,  380,  384,  386,  388,  390,  392,  394,  396,
      398,  610,  402,  310,  601,  782,  610,  605,  597,  613,
      782,  128,  782,  610,  595,  600,  607,  593,  596,  598,

      607,  782,  782,  589,  601,  586,  600,  602,  584,  595,
      595,  782,  584,  782,  782,  580,  578,  400,  404,  408,
      410,  415,  585,  416,  581,  579,  584,  578,  572,  576,
      570,  575,  582,  583,  561,  565,  577,  782,  569,  593,
      567,  782,  568,  573,  568,  557,  782,  566,  562,  556,
      571,  782,  420,  428,  434,  436,  438,  782,  549,    0,
      558,  556,  550,  547,  557,  577,  576,  549,  782,  553,
      555,  542,  554,  539,  782,  540,  537,  550,  549,  548,
      547,  540,  537,  544,  547,  782,  529,  525,  536,  543,
      530,  541,  536,  782,  534,  782,  521,  529,  519,  532,

      522,  531,  545,    0,    0,  521,  543,  525,  516,  525,
      523,  515,  522,  518,  782,  509,  782,  534,  502,  506,
      504,  530,  512,  528,  510,  495,  504,  524,  492,  505,
      496,  493,  489,  493,  488,  499,  497,  487,  485,  491,
      480,  483,  782,  494,  782,  479,  782,  491,  489,  487,
      486,  474,  470,  475,  479,  470,  467,  480,  475,  480,
      476,  476,  475,  478,  465,  463,  471,  782,  472,  455,
      459,  467,  468,  467,  458,  450,  454,  463,  451,  455,
      450,  459,  442,  446,  450,  782,  782,  444,  444,  442,
      451,  435,  435,  439,  432,  437,  445,  435,  438,  428,

      782,  441,  435,  439,  433,  782,  422,  782,  419,  413,
      401,  390,  393,  378,  320,  318,  323,  285,  278,  782,
      266,  244,  239,  234,  208,  175,  151,  118,  101,   91,
      782,   39,   19,  782,  782,  782,  782,  451,   50,  453,
      455,  457,  459
    } ;

static yyconst short int yy_def[544] =
    {   0,
      537,    1,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  538,  537,  537,  537,  539,
      540,  537,  537,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  538,  537,  537,  537,  541,
      542,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,

      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  543,  541,  540,  540,  537,  540,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  540,  537,  537,  540,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  540,  540,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,

      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  540,  537,  537,
      540,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  537,  540,  540,  540,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  540,  537,
      537,  540,  540,  540,  540,  540,  540,  540,  540,  540,
      540,  537,  540,  542,  542,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,

      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  540,  540,  540,
      540,  540,  537,  540,  542,  542,  542,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  540,  540,  540,  540,  540,  537,  542,  542,
      542,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  542,  542,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,

      537,  537,  537,  542,  542,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,

      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,    0,  537,  537,  537,
      537,  537,  537
    } ;

static yyconst short int yy_nxt[830] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
        4,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   21,   21,   25,   26,   27,   21,   21,
       28,   21,   21,   29,   30,   31,   32,   21,   21,   33,
       34,   21,   21,   35,   21,   21,   21,   36,   39,   36,
       38,   40,   60,   41,   42,   43,   44,   45,  536,   46,
       61,   47,   48,   61,   49,   50,   51,   52,   53,   54,
       55,   61,   61,   61,   61,   61,   61,   61,  535,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   66,
       61,   36,   74,   36,   69,   39,   63,   38,   67,  107,

       75,   64,   65,   71,   68,   72,   73,   61,   70,   76,
       61,  103,   61,  108,   77,   61,   79,   61,   78,  109,
       61,   87,   80,   84,   85,  112,   88,  104,  112,   90,
      534,   95,   89,   96,  110,  533,   91,   82,   81,   92,
       61,  149,   97,   61,   93,   61,   94,   61,   61,  116,
       61,   61,  532,  150,   61,   61,   61,   61,   61,   61,
       61,  114,   61,  332,   61,   61,  117,   61,   61,  118,
      333,   61,   61,   61,  155,   61,   61,  115,   61,   61,
      119,   61,   61,  156,   61,  122,  120,   61,  125,   61,
      531,   61,   61,  121,   61,   61,  160,  123,   61,  124,

      206,  207,   61,   61,  127,   61,   61,   61,  129,  530,
       61,  112,  161,  126,  112,  128,  131,   61,  166,   61,
       61,  130,   61,   61,  133,   61,   61,   61,   61,   61,
       61,  167,   61,  132,   61,   61,   61,   61,   61,   61,
      165,   61,  170,  529,   61,   61,  169,  171,   61,  174,
       61,   61,  168,   61,   61,  172,   61,  173,   61,   61,
      215,   61,   61,   61,  216,   61,   61,   61,  185,  528,
       61,  177,  178,  527,  176,   61,  175,  180,   61,  526,
      182,   61,  186,  187,   61,  181,   61,  179,   61,   61,
       61,   61,   61,   61,   61,   61,  525,   61,  221,   61,

      183,   61,   61,   61,   61,  218,   61,   61,  524,   61,
       61,  223,   61,  222,   61,   61,  225,   61,   61,   61,
      523,  232,   61,  224,  227,  226,  229,   61,  256,  257,
       61,  230,  234,   61,   61,  325,   61,   61,  231,  228,
       61,   61,  233,   61,   61,   61,   61,   61,   61,   61,
       61,  326,   61,  522,  272,   61,  235,   61,  521,  520,
       61,   61,  273,   61,   61,  269,   61,   61,  275,   61,
       61,  274,   61,   61,   61,  284,   61,   61,   61,  285,
      279,  276,   61,   61,  278,   61,   61,  277,   61,   61,
      280,  283,   61,   61,  281,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,  318,   61,   61,  519,   61,
       61,  319,   61,  518,   61,   61,  353,   61,   61,   61,
      517,  516,   61,  320,  355,  324,  356,   61,  354,  515,
       61,  357,  321,   61,  322,   61,   61,   61,   61,  514,
       61,   56,   56,   56,   62,   62,  113,  113,   61,   61,
      112,  112,  513,  512,  511,  510,  509,  508,  507,  506,
      505,  504,  503,  502,  501,  500,  499,  498,  497,  496,
      495,  494,  493,  492,  491,  490,  489,  488,  487,  486,
      485,  484,  483,  482,  481,  480,  479,  478,  477,  476,

      475,  474,  473,  472,  471,  470,  469,  468,  467,  466,
      465,  464,  463,  462,  461,  460,  459,  458,  457,  456,
      455,  454,  453,  452,  451,  450,  449,  448,  447,  446,
      445,  444,  443,  442,  441,  440,  439,  438,  437,  436,
      435,  434,  433,  432,  431,  430,  429,  428,  427,  426,
      425,  424,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  409,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  381,  380,  379,  378,  377,  376,

      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  352,  351,
      350,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  338,  337,  336,  335,  334,  331,  330,  329,
      328,  327,  323,  317,  316,  315,  314,  313,  312,  311,
      310,  309,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  282,  271,  270,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,

      244,  243,  242,  241,  240,  239,  238,  237,  236,  220,
      219,  217,  214,  213,  212,  211,  210,  209,  208,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  184,  164,  163,
      162,  159,  158,  157,  154,  153,  152,  151,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  139,  138,  137,
      136,  135,  134,   83,   57,  111,  106,  105,  102,  101,
      100,   99,   98,   86,   83,   59,   58,   57,   38,   37,
      537,    3,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,

      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537
    } ;

static yyconst short int yy_chk[830] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,   14,    5,
       14,   15,  539,   15,   15,   15,   15,   15,  533,   15,
       21,   15,   15,   21,   15,   15,   15,   15,   15,   15,
       15,   24,   25,   26,   24,   25,   26,   27,  532,   29,
       27,   28,   29,   30,   28,   31,   30,   32,   31,   25,
       32,   36,   29,   36,   26,   38,   24,   38,   25,   53,

       29,   24,   24,   27,   25,   28,   28,   33,   26,   30,
       33,   50,   34,   53,   31,   34,   32,   35,   31,   54,
       35,   42,   33,   40,   40,   60,   42,   50,   60,   43,
      530,   44,   42,   44,   54,  529,   43,   35,   34,   43,
       62,   99,   44,   62,   43,   63,   43,   64,   63,   65,
       64,   66,  528,   99,   66,   65,   67,   68,   65,   67,
       68,   63,   69,  292,   70,   69,   66,   70,   71,   66,
      292,   71,   72,   73,  104,   72,   73,   64,   74,   75,
       67,   74,   75,  104,   76,   70,   68,   76,   73,   77,
      527,   78,   77,   69,   78,   79,  108,   71,   79,   72,

      155,  155,   81,   80,   75,   81,   80,   82,   78,  526,
       82,  113,  108,   74,  113,   76,   80,  114,  116,  115,
      114,   79,  115,  117,   82,  118,  117,  122,  118,  119,
      122,  116,  119,   81,  120,  121,  123,  120,  121,  123,
      115,  124,  119,  525,  124,  125,  118,  120,  125,  123,
      126,  127,  117,  126,  127,  121,  128,  122,  129,  128,
      163,  129,  131,  130,  163,  131,  130,  132,  136,  524,
      132,  126,  127,  523,  125,  133,  124,  130,  133,  522,
      132,  168,  136,  136,  168,  131,  165,  129,  169,  165,
      170,  169,  171,  170,  173,  171,  521,  173,  168,  172,

      133,  174,  172,  175,  174,  165,  175,  177,  519,  176,
      177,  170,  176,  169,  178,  181,  172,  178,  181,  180,
      518,  179,  180,  171,  174,  173,  176,  179,  205,  205,
      179,  177,  181,  182,  183,  284,  182,  183,  178,  175,
      218,  221,  180,  218,  221,  222,  223,  224,  222,  223,
      224,  284,  225,  517,  221,  225,  182,  226,  516,  515,
      226,  227,  222,  228,  227,  218,  228,  229,  224,  230,
      229,  223,  230,  231,  233,  234,  231,  233,  234,  235,
      229,  225,  235,  269,  227,  272,  269,  226,  272,  273,
      230,  233,  273,  274,  231,  275,  274,  276,  275,  277,

      276,  278,  277,  279,  278,  280,  279,  281,  280,  318,
      281,  283,  318,  319,  283,  272,  319,  320,  514,  321,
      320,  275,  321,  513,  322,  324,  318,  322,  324,  353,
      512,  511,  353,  279,  320,  283,  321,  354,  319,  510,
      354,  322,  280,  355,  281,  356,  355,  357,  356,  509,
      357,  538,  538,  538,  540,  540,  541,  541,  542,  542,
      543,  543,  507,  505,  504,  503,  502,  500,  499,  498,
      497,  496,  495,  494,  493,  492,  491,  490,  489,  488,
      485,  484,  483,  482,  481,  480,  479,  478,  477,  476,
      475,  474,  473,  472,  471,  470,  469,  467,  466,  465,

      464,  463,  462,  461,  460,  459,  458,  457,  456,  455,
      454,  453,  452,  451,  450,  449,  448,  446,  444,  442,
      441,  440,  439,  438,  437,  436,  435,  434,  433,  432,
      431,  430,  429,  428,  427,  426,  425,  424,  423,  422,
      421,  420,  419,  418,  416,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  403,  402,  401,  400,  399,  398,
      397,  395,  393,  392,  391,  390,  389,  388,  387,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  376,  374,
      373,  372,  371,  370,  368,  367,  366,  365,  364,  363,
      362,  361,  359,  351,  350,  349,  348,  346,  345,  344,

      343,  341,  340,  339,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  323,  317,  316,
      313,  311,  310,  309,  308,  307,  306,  305,  304,  301,
      300,  299,  298,  297,  296,  295,  294,  290,  289,  288,
      287,  285,  282,  271,  268,  267,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  232,  220,  219,  217,  216,
      215,  213,  212,  211,  210,  209,  208,  207,  206,  204,
      203,  202,  201,  200,  198,  197,  196,  195,  194,  193,

      192,  191,  190,  189,  188,  187,  186,  185,  184,  167,
      166,  164,  162,  161,  160,  159,  158,  157,  156,  154,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  138,  137,  134,  111,  110,
      109,  107,  106,  105,  103,  102,  101,  100,   98,   97,
       96,   95,   94,   93,   92,   91,   90,   89,   88,   87,
       86,   85,   84,   83,   56,   55,   52,   51,   49,   48,
       47,   46,   45,   41,   39,   19,   17,   16,   12,    7,
        3,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,

      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#define INITIAL 0
/* lexpddl.lxi

Copyright C, 2002, F. Bacchus

Log:

Name		Date	Description

M Ady		020203	First Version

*/

/* lexpddl.c -- pddl language lexical analyzer

Copyright C, 2002, F. Bacchus

This module was created automatically from the file lexpddl.lxi.

Do not edit this file, edit and rebuild lexpddl.lxi instead.

Notes:
	1.  XList structures are not allocated for list punctuation.
*/

#include <ctype.h>
#include <setjmp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef WIN32 
#include <windows.h>
#endif /* WIN32 */

#include "tlplan.h"
#include "domain.h"
#include "formula.h"
#include "iface.h"
#include "lexpddl.h"
#include "list.h"
#include "makeform.h"
#include "plan.h"
#include "tlparse.h"
#include "tl_tab.h"
#include "util.h"

/* redefine input routine */

#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	result=(*pfYYInput)(buf,max_size)

/* yylval type */

#undef YYSTYPE
#define YYSTYPE XLISTP

/* yylex prototype */

#undef YY_DECL							/* lex yylex type */
#define YY_DECL int pddllex(YYSTYPE *pxValue)

/* handle unrecognized token */

#undef ECHO
#define ECHO \
	return(BADTOK)

/* XLIST structure types */

#define XATOM_IDENT		0				/* identifier */
#define XATOM_LIST		1				/* list */

typedef struct XList					/* XList element (atom) */
{
	struct XList *pxNext;				/* pointer to next */
	int nType;							/* atomic type (identifier or list) */
	int nCode;							/* token code */
	char *psValue;						/* string pointer */
	struct XList *pxValue;				/* list pointer */
}XLIST, *XLISTP;

/* local function prototypes */

static XLISTP NewXList
(
	int nType,							/* atomic type */
	int nCode,							/* token code */
	char *psName						/* literal (string) value */
);
static XLISTP CopyXList
(
	XLISTP px							/* xlist to copy */
);

//void yyerror
//(
//	char *ps							/* message to print */
//);
//int yy_input
//(
//	char *psBuf,
//	int nMaxSize
//);
//int (*pfYYInput)(char *, int);			/* lex input function pointer */

static XLISTP ParsePddl(void);
static BOOL ParseXList
(
	XLISTP pxParent						/* address of parent XList */
);
static BOOL TranslatePddlProblem
(
	XLISTP pxTree						/* parse tree */
);
static LISTP TranslateXList
(
	XLISTP pxList						/* XList pointer */ 
);
static int ListType
(
	int nCode							/* pddl token code */
);

static char *psDomain;					/* domain name */


YY_DECL;								/* yylex declaration */

/* token definitions */

#define	OPEN_BRAC	257
#define	CLOSE_BRAC	258
#define	OPEN_SQ	259
#define	CLOSE_SQ	260
#define	DEFINE	261
#define	DOMAIN	262
#define	REQS	263
#define	EQUALITY	264
#define	STRIPS	265
#define	ADL	266
#define	TYPING	267
#define	DISJUNCTIVE_PRECONDS	268
#define	EXT_PRECS	269
#define	UNIV_PRECS	270
#define	QUANT_PRECS	271
#define	COND_EFFS	272
#define	FLUENTS	273
#define	TIME	274
#define	DURATIVE_ACTIONS	275
#define	DURATION_INEQUALITIES	276
#define	CONTINUOUS_EFFECTS	277
#define	ACTION	278
#define	PROCESS	279
#define	EVENT	280
#define	DURATIVE_ACTION	281
#define	CONSTANTS	282
#define	PREDS	283
#define	FUNCTIONS	284
#define	TYPES	285
#define	ARGS	286
#define	PRE	287
#define	CONDITION	288
#define	START_PRE	289
#define	END_PRE	290
#define	EFFECTS	291
#define	INITIAL_EFFECT	292
#define	FINAL_EFFECT	293
#define	INVARIANT	294
#define	DURATION	295
#define	AT_START	296
#define	AT_END	297
#define	OVER_ALL	298
#define	AND	299
#define	OR	300
#define	EXISTS	301
#define	FORALL	302
#define	IMPLY	303
#define	NOT	304
#define	WHEN	305
#define	EITHER	306
#define	PROBLEM	307
#define	FORDOMAIN	308
#define	INITIALLY	309
#define	OBJECTS	310
#define	GOALS	311
#define	EQ	312
#define	LENGTH	313
#define	SERIAL	314
#define	PARALLEL	315
#define	METRIC	316
#define	MINIMIZE	317
#define	MAXIMIZE	318
#define	HASHT	319
#define	DURATION_VAR	320
#define	TOTAL_TIME	321
#define	INCREASE	322
#define	DECREASE	323
#define	SCALE_UP	324
#define	SCALE_DOWN	325
#define	ASSIGN	326
#define	GREATER	327
#define	GREATEQ	328
#define	LESS	329
#define	LESSEQ	330
#define	Q	331
#define	COLON	332
#define	BOGUS	333
#define	NAME	334
#define	FUNCTION_SYMBOL	335
#define	INTVAL	336
#define	FLOATVAL	337
#define	HYPHEN	338
#define	PLUS	339
#define	MUL	340
#define	DIV	341
#define	UMINUS	342
#define BADTOK 5000


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 538 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 782 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{*pxValue=0;return OPEN_BRAC;}
	YY_BREAK
case 2:
YY_RULE_SETUP
{*pxValue=0;return CLOSE_BRAC;}
	YY_BREAK
case 3:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,OPEN_SQ,yytext);return OPEN_SQ;}
	YY_BREAK
case 4:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,CLOSE_SQ,yytext);return CLOSE_SQ;}
	YY_BREAK
case 5:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,REQS,yytext);return REQS;}
	YY_BREAK
case 6:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,EQUALITY,yytext);return EQUALITY;}
	YY_BREAK
case 7:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,STRIPS,yytext);return STRIPS;}
	YY_BREAK
case 8:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,ADL,yytext);return ADL;}
	YY_BREAK
case 9:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,TYPING,yytext);return TYPING;}
	YY_BREAK
case 10:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,DISJUNCTIVE_PRECONDS,yytext);return DISJUNCTIVE_PRECONDS;}
	YY_BREAK
case 11:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,EXT_PRECS,yytext);return EXT_PRECS;}
	YY_BREAK
case 12:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,UNIV_PRECS,yytext);return UNIV_PRECS;}
	YY_BREAK
case 13:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,QUANT_PRECS,yytext);return QUANT_PRECS;}
	YY_BREAK
case 14:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,COND_EFFS,yytext);return COND_EFFS;}
	YY_BREAK
case 15:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,FLUENTS,yytext);return FLUENTS;}
	YY_BREAK
case 16:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,TIME,yytext);return TIME;}
	YY_BREAK
case 17:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,CONSTANTS,yytext);return CONSTANTS;}
	YY_BREAK
case 18:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,PREDS,yytext);return PREDS;}
	YY_BREAK
case 19:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,FUNCTIONS,yytext);return FUNCTIONS;}
	YY_BREAK
case 20:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,TYPES,yytext);return TYPES;}
	YY_BREAK
case 21:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,DURATIVE_ACTIONS,yytext);return DURATIVE_ACTIONS;}
	YY_BREAK
case 22:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,DURATION_INEQUALITIES,yytext);return DURATION_INEQUALITIES;}
	YY_BREAK
case 23:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,CONTINUOUS_EFFECTS,yytext);return CONTINUOUS_EFFECTS;}
	YY_BREAK
case 24:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,DEFINE,yytext);return DEFINE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,DOMAIN,yytext);return DOMAIN;}
	YY_BREAK
case 26:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,ACTION,yytext);return ACTION;}
	YY_BREAK
case 27:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,PROCESS,yytext);return PROCESS;}
	YY_BREAK
case 28:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,EVENT,yytext);return EVENT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,DURATIVE_ACTION,yytext);return DURATIVE_ACTION;}
	YY_BREAK
case 30:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,ARGS,yytext);return ARGS;}
	YY_BREAK
case 31:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,PRE,yytext);return PRE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,CONDITION,yytext);return CONDITION;}
	YY_BREAK
case 33:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,START_PRE,yytext);return START_PRE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,END_PRE,yytext);return END_PRE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,AT_START,yytext);return AT_START;}
	YY_BREAK
case 36:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,AT_END,yytext);return AT_END;}
	YY_BREAK
case 37:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,OVER_ALL,yytext);return OVER_ALL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,EFFECTS,yytext);return EFFECTS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,INITIAL_EFFECT,yytext);return INITIAL_EFFECT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,FINAL_EFFECT,yytext);return FINAL_EFFECT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,INVARIANT,yytext);return INVARIANT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,DURATION,yytext);return DURATION;}
	YY_BREAK
case 43:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,AND,yytext);return AND;}
	YY_BREAK
case 44:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,OR,yytext);return OR;}
	YY_BREAK
case 45:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,EXISTS,yytext);return EXISTS;}
	YY_BREAK
case 46:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,FORALL,yytext);return FORALL;}
	YY_BREAK
case 47:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,IMPLY,yytext);return IMPLY;}
	YY_BREAK
case 48:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,NOT,yytext);return NOT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,WHEN,yytext);return WHEN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,EITHER,yytext);return EITHER;}
	YY_BREAK
case 51:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,PROBLEM,yytext);return PROBLEM;}
	YY_BREAK
case 52:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,FORDOMAIN,yytext);return FORDOMAIN;}
	YY_BREAK
case 53:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,OBJECTS,yytext);return OBJECTS;}
	YY_BREAK
case 54:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,INITIALLY,yytext);return INITIALLY;}
	YY_BREAK
case 55:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,GOALS,yytext);return GOALS;}
	YY_BREAK
case 56:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,EQ,yytext);return EQ;}
	YY_BREAK
case 57:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,LENGTH,yytext);return LENGTH;}
	YY_BREAK
case 58:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,SERIAL,yytext);return SERIAL;}
	YY_BREAK
case 59:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,PARALLEL,yytext);return PARALLEL;}
	YY_BREAK
case 60:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,METRIC,yytext);return METRIC;}
	YY_BREAK
case 61:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,MINIMIZE,yytext);return MINIMIZE;}
	YY_BREAK
case 62:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,MAXIMIZE,yytext);return MAXIMIZE;}
	YY_BREAK
case 63:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,HASHT,yytext);return HASHT;}
	YY_BREAK
case 64:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,DURATION_VAR,yytext);return DURATION_VAR;}
	YY_BREAK
case 65:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,TOTAL_TIME,yytext);return TOTAL_TIME;}
	YY_BREAK
case 66:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,INCREASE,yytext);return INCREASE;}
	YY_BREAK
case 67:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,DECREASE,yytext);return DECREASE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,SCALE_UP,yytext);return SCALE_UP;}
	YY_BREAK
case 69:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,SCALE_DOWN,yytext);return SCALE_DOWN;}
	YY_BREAK
case 70:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,ASSIGN,yytext);return ASSIGN;}
	YY_BREAK
case 71:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,PLUS,yytext);return PLUS;}
	YY_BREAK
case 72:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,HYPHEN,yytext);return HYPHEN;}
	YY_BREAK
case 73:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,MUL,yytext);return MUL;}
	YY_BREAK
case 74:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,DIV,yytext);return DIV;}
	YY_BREAK
case 75:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,GREATER,yytext);return GREATER;}
	YY_BREAK
case 76:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,GREATEQ,yytext);return GREATEQ;}
	YY_BREAK
case 77:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,LESS,yytext);return LESS;}
	YY_BREAK
case 78:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,LESSEQ,yytext);return LESSEQ;}
	YY_BREAK
case 79:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,Q,yytext);return Q;}
	YY_BREAK
case 80:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,COLON,yytext);return COLON;}
	YY_BREAK
case 81:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,NAME,yytext);return(NAME);}
	YY_BREAK
case 82:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,NAME,yytext);return(NAME);}
	YY_BREAK
case 83:
YY_RULE_SETUP
;
	YY_BREAK
case 84:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
;
	YY_BREAK
case 85:
YY_RULE_SETUP
{nLineNumber++;};
	YY_BREAK
case 86:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,INTVAL,yytext);return(INTVAL);}
	YY_BREAK
case 87:
YY_RULE_SETUP
{*pxValue=NewXList(XATOM_IDENT,FLOATVAL,yytext);return(FLOATVAL);}
	YY_BREAK
case 88:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 538 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 538 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 537);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif


/* ParsePddl -------------------------------------------------------------------

Description:
	Open the specified pddl problem file.  Parse the input and execute it.
*/

static XLISTP ParsePddl(void)
{
	XLISTP px;							/* parse tree */

	/* allocate parent list */
	
	px=(XLISTP)MemAlloc(sizeof(XLIST));
	px->nType=XATOM_LIST;

	ParseXList(px);

	return px;
}

/* ParseXList

Description:
	Simple recursive descent list parser.
*/

static BOOL ParseXList
(
	XLISTP pxParent						/* address of parent XList */
)
{
	XLISTP pxNested;					/* nested XList */
	XLISTP pxValue;						/* token value */
	XLISTP *ppxNext;					/* address of next pointer */
	int nCode;

	ppxNext=&pxParent->pxValue;
	for(;;)
	{
		nCode=pddllex(&pxValue);
		switch(nCode)
		{
			case 0:						/* ??? */
				return TRUE;
			case EOF:
				fprintf(stderr,"Unexpected end of file\n");
				return FALSE;
			case OPEN_BRAC:				/* nested list */
				pxNested=NewXList(XATOM_LIST,0,0);
				*ppxNext=pxNested;
				ppxNext=&pxNested->pxNext;
				if(!ParseXList(pxNested))
					return FALSE;
				break;
			case CLOSE_BRAC:			/* end of list, return */
				return TRUE;
			default:
				*ppxNext=pxValue;
				ppxNext=&pxValue->pxNext;
		}
	}
	return TRUE;
}

/* LoadPddlProblem

Description:
	Open the specified pddl problem file.  Parse the input and execute it.
*/

DECLSPEC void LoadPddlProblem
(
	char *psFile						/* file name */
)
{
	FILE *pfInputSaved;					/* saved input file stream */
	YY_BUFFER_STATE ybfSaved;			/* saved buffer state */
	int nLineNumberSaved;				/* saved line number */
	char *psCurrentFileSaved;			/* saved file name */
	BOOL bInteractiveModeSaved;			/* saved interactive mode */
	XLISTP pxTree;						/* parse tree */

	dfPddlTime=GetInternalRunTime();	/* start our timer */

	/* push our current file context */

	pfInputSaved=pfInput;
	nLineNumberSaved=nLineNumber;
	bInteractiveModeSaved=bInteractiveMode;
	psCurrentFileSaved=psCurrentFile;

	/* open the file */

	if((int)psFile>0)
	{
		bInteractiveMode=FALSE;
		if(bVerbose)
			Message("Loading PDDL file: %s\n",psFile);
		pfInput=fopen(psFile,"r");
		if(!pfInput)
		{	
			ErrorMessage("Failed to open PDDL file %s\n",psFile);
			perror("File open failure");
			goto cleanup;
		}
	}
	else if(!psFile)
	{
		bInteractiveMode=TRUE;
		if(bVerbose)
			Message("Opening interactive session...\n");
		pfInput=stdin;
	}
	else
	{
		bInteractiveMode=TRUE;
		pfInput=0;
	}

	if(pfInput==stdin)
	{
		psCurrentFile=(char *)malloc(strlen("interactive session")+1);
		strcpy(psCurrentFile,"interactive session");
	}
	else if(!pfInput)
	{
		psCurrentFile=(char *)malloc(strlen("window session")+1);
		strcpy(psCurrentFile,"window session");
	}
	else
	{
		psCurrentFile=(char *)malloc(strlen(psFile)+1);
		strcpy(psCurrentFile,psFile);
	}

	ybfSaved=YY_CURRENT_BUFFER;
	if(ybfSaved)
		yy_switch_to_buffer(yy_create_buffer(pfInput,YY_BUF_SIZE));

	/* read in the file */

	nLineNumber=1;
	if(bInteractiveMode)
		CommandPrintf(stdout,"OK> ");
	pxTree=ParsePddl();
	TranslatePddlProblem(pxTree->pxValue);

	/* clean up */

	if(pfInput&&pfInput!=stdin)
		fclose(pfInput);
	free(psCurrentFile);

	/* pop our saved file context */

	if(ybfSaved)
		yy_switch_to_buffer(ybfSaved);	/* restore saved buffer */
cleanup:
	pfInput=pfInputSaved;
	nLineNumber=nLineNumberSaved;
	bInteractiveMode=bInteractiveModeSaved;
	psCurrentFile=psCurrentFileSaved;
}

/* TranslatePDDLProblem

Description:
	Write out a pddl parse tree in tlplan format.
*/
static BOOL TranslatePddlProblem
(
	XLISTP pxTree						/* parse tree */
)
{
	XLISTP px;							/* parse tree pointer */
	XLISTP px1;							/* parse tree pointer */
	XLISTP px2;							/* parse tree pointer */
	XLISTP px3;							/* parse tree pointer */
	XLISTP pxSave;						/* parse tree pointer */
	CELLP pcCommand;					/* command cell pointer */
	char acBuf[256];					/* format buffer */
	LISTP plStart,plEnd;				/* list head */
	LISTP plStart1,plEnd1;				/* list head */
	LISTP plStart2,plEnd2;				/* list head */
	XLISTP pxStart,pxEnd;				/* xlist head */
	LITVAL lvDomain;					/* domain name */
	SYMBOLP psSymbol;					/* symbol table entry */
			
	char *psProblem;					/* problem name */

	if(pxTree->nType!=XATOM_LIST)
	{
		fprintf(stderr,"load-pddl-problem:  Expected a list.\n");
		return FALSE;
	}
	px=pxTree->pxValue;
	if(!px||px->nCode!=DEFINE)
	{
		fprintf(stderr,"load-pddl-problem:  Expected \"define\"\n");
		return FALSE;
	}

	px=px->pxNext;
	if(!px||px->nType!=XATOM_LIST)
	{
		fprintf(stderr,"load-pddl-problem:  Expected a problem list.\n");
		return FALSE;
	}
	px1=px->pxValue;
	if(px1->nCode!=PROBLEM)
	{
		fprintf(stderr,"load-pddl-problem:  Expected \"problem\"\n");
		return FALSE;
	}

	px1=px1->pxNext;
	if(px1->nCode!=NAME)
	{
		fprintf(stderr,"load-pddl-problem:  Expected problem name\n");
		return FALSE;
	}
	psProblem=px1->psValue;				/* save problem name */
	pxSave=px;							/* save our context */

	for(px=pxSave;px;px=px->pxNext)
	{
		if(px->nType!=XATOM_LIST)
		{
			fprintf(stderr,"load-pddl-problem:  Expected a list.\n");
			return FALSE;
		}
	}

	// the domain
	
	psDomain=NULL;
	for(px=pxSave;px;px=px->pxNext)
	{
		px1=px->pxValue;
		switch(px1->nCode)
		{
			case FORDOMAIN:
				px1=px1->pxNext;
				if(px1->nCode!=NAME)
				{
					fprintf(stderr,"load-pddl-problem:  Expected domain name\n");
					return FALSE;
				}
				psDomain=px1->psValue;
				lvDomain.psString=psDomain;
				pcCommand=CompileArgForm(&aLoadDomainAction,MakeLiteralForm(ATOM_IDENT,lvDomain));
				(*pcCommand->pfForm->paAction->pfEval)(pcCommand,plpCurrentPlan,pbGlobalVariables);
				break;
		}
	}

	// the objects list
	// we ignore types that have not been declared

	for(px=pxSave;px;px=px->pxNext)
	{
		px1=px->pxValue;
		switch(px1->nCode)
		{
			case OBJECTS:
				pxStart=NULL;			/* initialize object xlist */
				pxEnd=(XLISTP)&pxStart;

				px1=px1->pxNext;		/* point to first object name */
				for(px2=px1;px2;px2=px2->pxNext)	/* scan object list for next type */
				{
					if(px2->nCode==HYPHEN)	/* next token is type if we see a hyphen */
					{
						px3=px2;		/* save pointer to terminating token */
						px2=px2->pxNext;	/* point to type */
						if(!px2)
						{
							fprintf(stderr,"load-pddl-problem:  Unexpected end of object list\n");
							return FALSE;
						}
						if(SymbolLookup(strlwr(px2->psValue),&psSymbol))	/* if this is a domain symbol */
						{
							for(;px1!=px3;px1=px1->pxNext)	/* for all objects of this type */
							{
								pxEnd=pxEnd->pxNext=NewXList(XATOM_LIST,0,NULL);	/* create a (type name) list */
								pxEnd->pxValue=NewXList(XATOM_IDENT,NAME,px2->psValue);
								pxEnd->pxValue->pxNext=CopyXList(px1);
							}
						}
						px1=px2->pxNext;	/* point to next object name */
					}
				}
				break;
		}
	}

	// the initial state
	
	for(px=pxSave;px;px=px->pxNext)
	{
		px1=px->pxValue;
		switch(px1->nCode)
		{
			case INITIALLY:
				plStart=NULL;
				plEnd=(LISTP)&plStart;
				plEnd=plEnd->plNext=NewList(ATOM_IDENT,"define");
				sprintf(acBuf,"state-%s",psProblem);
				plEnd=plEnd->plNext=NewList(ATOM_IDENT,acBuf);

				/* translate object list */

				for(px2=pxStart;px2;px2=px2->pxNext)
					plEnd=plEnd->plNext=TranslateXList(px2);

				/* translate initial world */
				
				for(px1=px1->pxNext;px1;px1=px1->pxNext)
					plEnd=plEnd->plNext=TranslateXList(px1);
				
				plStart=NewList(ATOM_LISTP,"",plStart);	/* enclose list */
				ExecuteList(plStart);
				break;
		}
	}

	// the goal
	
	if(stricmp(psDomain,"taxi"))			// kludge alert!!!
	{
		for(px=pxSave;px;px=px->pxNext)
		{
			px1=px->pxValue;
			switch(px1->nCode)
			{
				case GOALS:
	
					// first remove outer conjunction

					px2=px1->pxNext;
					if(!px2||px2->nType!=XATOM_LIST)
					{
						fprintf(stderr,"load-pddl-problem:  Expected a list.\n");
						return FALSE;
					}
					px2=px2->pxValue;
					if(px2->nCode==AND)
						px1=px2;

					plStart=NULL;
					plEnd=(LISTP)&plStart;
					plEnd=plEnd->plNext=NewList(ATOM_IDENT,"define");
					sprintf(acBuf,"goal-%s",psProblem);
					plEnd=plEnd->plNext=NewList(ATOM_IDENT,acBuf);
					for(px1=px1->pxNext;px1;px1=px1->pxNext)
						plEnd=plEnd->plNext=TranslateXList(px1);
					plStart=NewList(ATOM_LISTP,"",plStart);
					ExecuteList(plStart);
					break;
			}
		}

		// set-goal

		plStart=NULL;
		plEnd=(LISTP)&plStart;
		plEnd=plEnd->plNext=NewList(ATOM_IDENT,"set-goal");
		sprintf(acBuf,"goal-%s",psProblem);
		plEnd=plEnd->plNext=NewList(ATOM_LISTP,"",NewList(ATOM_IDENT,acBuf));
		plStart=NewList(ATOM_LISTP,"",plStart);
		ExecuteList(plStart);
	}
	
	// set-initial-world

	plStart=NULL;
	plEnd=(LISTP)&plStart;
	plEnd=plEnd->plNext=NewList(ATOM_IDENT,"set-initial-world");
	sprintf(acBuf,"state-%s",psProblem);
	plEnd=plEnd->plNext=NewList(ATOM_LISTP,"",NewList(ATOM_IDENT,acBuf));
	plStart=NewList(ATOM_LISTP,"",plStart);
	ExecuteList(plStart);

	// set-plan-name
	
	pcCommand=CompileArgForm(&aSetPlanNameAction,MakeStringForm(psCurrentFile));
	(*pcCommand->pfForm->paAction->pfEval)(pcCommand,plpCurrentPlan,pbGlobalVariables);

	// set-heuristic-fn or set-priority-fn
	
	if(nPddlSupport!=PDDL_IGNORE_METRIC)
	{
		for(px=pxSave;px;px=px->pxNext)
		{
			px1=px->pxValue;
			switch(px1->nCode)
			{
				case METRIC:
					plStart=NULL;			// initialize list head
					plEnd=(LISTP)&plStart;

					/* def-defined-function */

					plEnd=plEnd->plNext=NewList(ATOM_IDENT,"def-defined-function");
					plEnd=plEnd->plNext=NewList(ATOM_LISTP,"",NewList(ATOM_IDENT,"metric"));

					px2=px1->pxNext;		// point to minimize/maximize
					px3=px2->pxNext;		// point to expression to evaluate

					/* translate expression */

					plStart1=NULL;			// initialize list head
					plEnd1=(LISTP)&plStart1;
					if((px2->nCode==MAXIMIZE)!=(nPddlSupport==PDDL_PRIORITY_METRIC))	// invert formula for maximize xor priority
					{
						plEnd1=plEnd1->plNext=NewList(ATOM_IDENT,"*");
						plEnd1=plEnd1->plNext=NewList(ATOM_FLOAT,"-1.0");
					}				
					plEnd1=plEnd1->plNext=TranslateXList(px3);
					if(px2->nCode==MAXIMIZE)
						plStart1=NewList(ATOM_LISTP,"",plStart1);	/* enclose list */

					/* assign value */

					plStart2=NULL;			// initialize list head
					plEnd2=(LISTP)&plStart2;
					plEnd2=plEnd2->plNext=NewList(ATOM_IDENT,":=");
					plEnd2=plEnd2->plNext=NewList(ATOM_IDENT,"metric");
					plEnd2->plNext=plStart1;
					plStart2=NewList(ATOM_LISTP,"",plStart2);	/* enclose list */

					plEnd=plEnd->plNext=plStart2;
					plStart=NewList(ATOM_LISTP,"",plStart);	/* enclose list */
					ExecuteList(plStart);

					/* set-heuristic-fn or set-priority-fn */
				
					plStart1=NewList(ATOM_IDENT,"metric");
					plStart1=NewList(ATOM_LISTP,"",plStart1);	/* enclose list */
					if(nPddlSupport=PDDL_COST_METRIC)
						plStart=NewList(ATOM_IDENT,"set-heuristic-fn");
					else
						plStart=NewList(ATOM_IDENT,"set-priority-fn");
					plStart->plNext=plStart1;
					plStart=NewList(ATOM_LISTP,"",plStart);	/* enclose list */
					ExecuteList(plStart);
					break;
			}
		}
	}

//	// plan
//
//	pcCommand=CompileArgForm(&aPlanAction,NULL);
//	(*pcCommand->pfForm->paAction->pfEval)(pcCommand,plpCurrentPlan,pbGlobalVariables);

	return TRUE;
}

/* TranslateXList

Description:
	Recursive routine to translate an XList
*/

static LISTP TranslateXList
(
	XLISTP pxList						/* list pointer */ 
)
{
	LISTP plStart,plEnd;				/* list head */
	XLISTP px;							/* XList pointer */
	
	plStart=NULL;
	plEnd=(LISTP)&plStart;

	// translate elements
	
	for(px=pxList->pxValue;px;px=px->pxNext)
	{
		if(px->nType==XATOM_LIST)
			plEnd=plEnd->plNext=TranslateXList(px);
		else
		{
			if(!stricmp(psDomain,"zeno-travel"))	/* kludge alert! */
			{
				if(!stricmp(px->psValue,"next"))
				{
					px->psValue=(char *)MemAlloc(strlen("fuel-next")+1);
					strcpy(px->psValue,"fuel-next");
				}
			}
			plEnd=plEnd->plNext=NewList(ListType(px->nCode),px->psValue);
		}
	}
	return NewList(ATOM_LISTP,"",plStart);
}

/* ListType

Description:
	Convert an XLIST token type to a LIST atom type.
*/

static int ListType
(
	int nCode							/* pddl token code */
)
{
	switch(nCode)
	{
		case INTVAL:
			return ATOM_INTEGER;
		case FLOATVAL:
			return ATOM_FLOAT;
	}
	return ATOM_IDENT;					/* everything else is an ident */
}

/* NewXList

Description:
	Allocate and fill in a single xlist element.
*/

static XLISTP NewXList
(
	int nType,							/* atomic type */
	int nCode,							/* token code */
	char *psName						/* literal (string) value */
)
{
	XLISTP px;							/* XList pointer */

	px=(XLISTP)MemAlloc(sizeof(XLIST));
	px->nType=nType;
	px->nCode=nCode;
	if(psName)
	{
		px->psValue=(char *)MemAlloc(strlen(psName)+1);
		strcpy(px->psValue,psName);
	}
	return px;
}

/* CopyXList

Description:
	Allocate and fill in a single xlist element.
	The pxNext and pxValue pointers are explicitly zeroed.
*/

static XLISTP CopyXList
(
	XLISTP px							/* xlist to copy */
)
{
	XLISTP pxNew;						/* new XList pointer */

	pxNew=(XLISTP)MemAlloc(sizeof(XLIST));
	memcpy(pxNew,px,sizeof(XLIST));
	pxNew->pxNext=NULL;
	pxNew->pxValue=NULL;
	return pxNew;
}


int yywrap()
{
	return 1;
};
