(define (problem comm_5_2)
  (:domain comm)
  (:objects s1 s2 s3 s4 - stage p0 p1 - packet)
  (:init (and (current-stage s0)
              (in-channel p0) (seq-number p0 s0) (oneof (noisy p0) (not (noisy p0)))
              (in-channel p1) (seq-number p1 s1) (oneof (noisy p1) (not (noisy p1)))
              (next-stage s0 s1)
              (next-stage s1 s2)
              (next-stage s2 s3)
              (next-stage s3 s4)
         )
  )
  (:goal (and (ok p0) (ok p1)))
)
