#This makefile was written for GNU make. It may or may not work
#with other make utilities.


####### FLAGS 

CC  =   g++  


#The libraries will be built using ar. If ar needs different flags
#insert them here.
# AR = ar -cr

##############################################################################
#Do not change anything below this line                                      #
############################################################################## 

MAKEFILE = Makefile


SUBDIRS = src

all: 
	g++ *.cc -I. -o merge

clean: 
	rm *.o 






