(DEFINE (PROBLEM FIX-STRIPS1) 
    (:DOMAIN FLAT-TIRE-STRIPS)
  (:objects wheel1 wheel2 the-hub nuts trunk)
  (:init (WHEEL WHEEL1) (WHEEL WHEEL2) (HUB the-HUB) (NUT NUTS) (CONTAINER TRUNK)
	  (IN JACK TRUNK) (IN PUMP TRUNK) (IN WHEEL2 TRUNK)
	  (IN WRENCH TRUNK) (ON WHEEL1 the-HUB) (ON-GROUND the-HUB) (TIGHT NUTS the-HUB)
	  (NOT (LOCKED TRUNK)) (NOT (OPEN TRUNK)) (NOT (UNFASTENED the-HUB))
	  )
  (:GOAL (AND (in WHEEL1 trunk) (in jack trunk) (in pump trunk)))
  (:length (:serial 9) (:parallel 9)))
