; state06 in TLPLAN
;    (:length (:parallel 30))	

(define (problem state6) 
    (:domain flat-tire-strips) 
    (:objects wheel1 wheel2 wheel3 wheel4 wheela wheela wheelb wheelc wheeld
	boot nuts hub1 hub2 hub3 hub4)
    (:init 
	(wheel wheel1) (wheel wheel2) (wheel wheel3) (wheel wheel4)
	(wheel wheela) (wheel wheelb) (wheel wheelc) (wheel wheeld)
	(hub hub1) (hub hub2) (hub hub3) (hub hub4)
	(container boot) (nut nuts) 
	(not (inflated wheel1)) (not (inflated wheel2)) 
	(not (inflated wheel3)) (not (inflated wheel4))
        (not (inflated wheela)) (not (inflated wheelb)) 
 	(not (inflated wheelc)) (not (inflated wheeld))
	(on wheel1 hub1) (on wheel2 hub2) (on wheel3 hub3) (on wheel4 hub4)
	(on-ground hub1) (on-ground hub2) (on-ground hub3) (on-ground hub4)
	(not (unfastened hub1)) (not (unfastened hub2))
	(not (unfastened hub3)) (not (unfastened hub4)) 
	(tight nuts hub1) (tight nuts hub2) 
	(tight nuts hub3) (tight nuts hub4)
	(intact wheela) (intact wheelb) (intact wheelc) (intact wheeld)
	(in jack boot) (in pump boot) (in wrench boot)
	(in wheela boot) (in wheelb boot) (in wheelc boot) (in wheeld boot)
	(not (locked boot)) (not (open boot)))

    (:goal (and (inflated wheela) (inflated wheelb) (inflated wheelc) 
     	(inflated wheeld) (on wheela hub1) (on wheelb hub2)
	(on wheelc hub3) (on wheeld hub4) 
	(tight nuts hub1) (tight nuts hub2) 
	(tight nuts hub3) (tight nuts hub4)
	(on-ground hub1) (on-ground hub2) (on-ground hub3)
	(in jack boot) (in pump boot) (in wheel1 boot) 
	(in wrench boot) (not (open boot))))
)
