(define (problem s2)
  (:domain sortnet)
  (:objects l1 l2 - line)
  (:init (and (less l1 l2)
              (oneof (high l1) (not (high l1)))
              (oneof (high l2) (not (high l2)))
         )
  )
  (:goal (and (or (not (high l1)) (high l2))
         )
  )
)
