(define (problem s3)
  (:domain sortnet)
  (:objects l1 l2 l3 - line)
  (:init (and (less l1 l2)
              (less l1 l3)
              (less l2 l3)
              (oneof (high l1) (not (high l1)))
              (oneof (high l2) (not (high l2)))
              (oneof (high l3) (not (high l3)))
         )
  )
  (:goal (and (or (not (high l1)) (high l2))
              (or (not (high l2)) (high l3))
         )
  )
)
