/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Brazil.
 *
 * The Initial Developer of the Original Code is
 * National ICT Australia.
 * Portions created by the Initial Developer are Copyright (C) 2007
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *	Douglas Aberdeen	(doug.aberdeen@gmail.com)
 *	Owen Thomas		(owen.thomas@nicta.com.au)
 *	Olivier Buffet		(olivier.buffet@loria.fr)
 *
 * ***** END LICENSE BLOCK ***** */
/*
 *  BrazilMainWindow.h
 *  
 *
 *  Created by Owen Thomas on 6/09/06.
 *  
 *
 */

#ifndef brazil_main_window
#define brazil_main_window

#include <QWidget>
#include <QMainWindow>
#include <QStackedLayout>

#include <xercesc/parsers/XercesDOMParser.hpp>
#include <xercesc/sax/HandlerBase.hpp>
#include <xercesc/util/PlatformUtils.hpp>

#include "../BrazilPlanningWrapper.h"
#include "../BrazilStateList.h"

#include "../../dynamic-gantt/GanttChart.h"
#include "../statistics/StatsWidget.h"

#include "BrazilConfiguration.h"
#include "SideMenu.h"


class BrazilApplication;
class DOMDomain;
class ActionWidgetFactory;
class ResultBar;
class QString;

XERCES_CPP_NAMESPACE_USE

class BrazilMainWindow : public QMainWindow {

	Q_OBJECT
	protected:
		SideMenu* sideMenu;
		
		XercesDOMParser* parser;
		QString openFileName;
		QString newDomainFileName;
		DOMDomain* domain;
		
		BrazilApplication* brazilDefinition;
		GanttChart* ganttChart;
		StatsWidget* statsWidget;
		
		ResultBar* resultBar;
		
		BrazilPlanningWrapper* planner;
		QStackedLayout* rightSplitterLayout;
		
		BrazilConfiguration* config;
		
		int sideMenuMaxWidth, sideMenuMinWidth;
		
		//A List of median states generated by the
		//BrazilPlanningWrapper planner.
		BrazilStateList* medianStates;

		// List of last N stocahstic states generated
		BrazilStateList* stochasticStates;
	
	protected slots:
	
		void openDomain ();
		
		void saveDomain ();
		
		void saveAsDomain ();
		
		void newDomain ();
		
			//When the gantt chart starts drawing a state, lock down the size
		//of the side menu - to stop it chaning shape.
		void handleStartDrawFromState () {
			sideMenuMinWidth = sideMenu->minimumWidth();
			sideMenuMaxWidth = sideMenu->maximumWidth ();
			sideMenu->setMinimumWidth (sideMenu->width ());
			sideMenu->setMaximumWidth (sideMenu->width ());
		}
		
		void handleEndDrawFromState () {
			sideMenu->setMinimumWidth (sideMenuMinWidth);
			sideMenu->setMaximumWidth (sideMenuMaxWidth);
		}
		
				
	public:
		
		BrazilMainWindow (DOMDomain& domain, QMainWindow* actionEditorWindow, 
			ActionWidgetFactory* awfactory, XercesDOMParser* parser, 
			BrazilConfiguration* config, QString newDomainFileName);
		
		void setDomain (DOMDomain& newDomain);
		
};

#endif


